/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type AddParticipantRequest = {
  /**
   * Phone number (E.164 format) or email address of the participant to add
   */
  handle: string;
};

/** @internal */
export type AddParticipantRequest$Outbound = {
  handle: string;
};

/** @internal */
export const AddParticipantRequest$outboundSchema: z.ZodMiniType<
  AddParticipantRequest$Outbound,
  AddParticipantRequest
> = z.object({
  handle: z.string(),
});

export function addParticipantRequestToJSON(
  addParticipantRequest: AddParticipantRequest,
): string {
  return JSON.stringify(
    AddParticipantRequest$outboundSchema.parse(addParticipantRequest),
  );
}
