/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import {
  SupportedContentType,
  SupportedContentType$inboundSchema,
} from "./supported-content-type.js";

/**
 * Current upload/processing status
 */
export const AttachmentStatus = {
  Pending: "pending",
  Complete: "complete",
  Failed: "failed",
} as const;
/**
 * Current upload/processing status
 */
export type AttachmentStatus = OpenEnum<typeof AttachmentStatus>;

export type Attachment = {
  /**
   * Unique identifier for the attachment (UUID)
   */
  id: string;
  /**
   * Original filename of the attachment
   */
  filename: string;
  /**
   * Supported MIME types for file attachments and media URLs.
   *
   * @remarks
   *
   * **Images:** image/jpeg, image/png, image/gif, image/heic, image/heif, image/tiff, image/bmp
   *
   * **Videos:** video/mp4, video/quicktime, video/mpeg, video/3gpp
   *
   * **Audio:** audio/mpeg, audio/mp4, audio/x-m4a, audio/x-caf, audio/wav, audio/aiff, audio/aac, audio/amr
   *
   * **Documents:** application/pdf, text/plain, text/vcard, text/rtf, text/csv, text/html, text/calendar, application/msword, application/vnd.openxmlformats-officedocument.wordprocessingml.document, application/vnd.ms-excel, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-powerpoint, application/vnd.openxmlformats-officedocument.presentationml.presentation, application/vnd.apple.pages, application/vnd.apple.numbers, application/vnd.apple.keynote, application/epub+zip, application/zip
   *
   * **Unsupported:** WebP, SVG, FLAC, OGG, and executable files are explicitly rejected.
   */
  contentType: SupportedContentType;
  /**
   * Size of the attachment in bytes
   */
  sizeBytes: number;
  /**
   * Current upload/processing status
   */
  status: AttachmentStatus;
  /**
   * URL to download the attachment
   */
  downloadUrl?: string | undefined;
  /**
   * When the attachment was created
   */
  createdAt: Date;
};

/** @internal */
export const AttachmentStatus$inboundSchema: z.ZodMiniType<
  AttachmentStatus,
  unknown
> = openEnums.inboundSchema(AttachmentStatus);

/** @internal */
export const Attachment$inboundSchema: z.ZodMiniType<Attachment, unknown> = z
  .pipe(
    z.object({
      id: types.string(),
      filename: types.string(),
      content_type: SupportedContentType$inboundSchema,
      size_bytes: types.number(),
      status: AttachmentStatus$inboundSchema,
      download_url: types.optional(types.string()),
      created_at: types.date(),
    }),
    z.transform((v) => {
      return remap$(v, {
        "content_type": "contentType",
        "size_bytes": "sizeBytes",
        "download_url": "downloadUrl",
        "created_at": "createdAt",
      });
    }),
  );

export function attachmentFromJSON(
  jsonString: string,
): SafeParseResult<Attachment, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Attachment$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Attachment' from JSON`,
  );
}
