/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

/**
 * Payload for chat.typing_indicator.started webhook events
 */
export type ChatTypingIndicatorStartedEvent = {
  /**
   * Chat identifier
   */
  chatId: string;
};

/** @internal */
export const ChatTypingIndicatorStartedEvent$inboundSchema: z.ZodMiniType<
  ChatTypingIndicatorStartedEvent,
  unknown
> = z.pipe(
  z.object({
    chat_id: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "chat_id": "chatId",
    });
  }),
);
/** @internal */
export type ChatTypingIndicatorStartedEvent$Outbound = {
  chat_id: string;
};

/** @internal */
export const ChatTypingIndicatorStartedEvent$outboundSchema: z.ZodMiniType<
  ChatTypingIndicatorStartedEvent$Outbound,
  ChatTypingIndicatorStartedEvent
> = z.pipe(
  z.object({
    chatId: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      chatId: "chat_id",
    });
  }),
);

export function chatTypingIndicatorStartedEventToJSON(
  chatTypingIndicatorStartedEvent: ChatTypingIndicatorStartedEvent,
): string {
  return JSON.stringify(
    ChatTypingIndicatorStartedEvent$outboundSchema.parse(
      chatTypingIndicatorStartedEvent,
    ),
  );
}
export function chatTypingIndicatorStartedEventFromJSON(
  jsonString: string,
): SafeParseResult<ChatTypingIndicatorStartedEvent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ChatTypingIndicatorStartedEvent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChatTypingIndicatorStartedEvent' from JSON`,
  );
}
