/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

/**
 * Payload for chat.typing_indicator.stopped webhook events
 */
export type ChatTypingIndicatorStoppedEvent = {
  /**
   * Chat identifier
   */
  chatId: string;
};

/** @internal */
export const ChatTypingIndicatorStoppedEvent$inboundSchema: z.ZodMiniType<
  ChatTypingIndicatorStoppedEvent,
  unknown
> = z.pipe(
  z.object({
    chat_id: types.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "chat_id": "chatId",
    });
  }),
);
/** @internal */
export type ChatTypingIndicatorStoppedEvent$Outbound = {
  chat_id: string;
};

/** @internal */
export const ChatTypingIndicatorStoppedEvent$outboundSchema: z.ZodMiniType<
  ChatTypingIndicatorStoppedEvent$Outbound,
  ChatTypingIndicatorStoppedEvent
> = z.pipe(
  z.object({
    chatId: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      chatId: "chat_id",
    });
  }),
);

export function chatTypingIndicatorStoppedEventToJSON(
  chatTypingIndicatorStoppedEvent: ChatTypingIndicatorStoppedEvent,
): string {
  return JSON.stringify(
    ChatTypingIndicatorStoppedEvent$outboundSchema.parse(
      chatTypingIndicatorStoppedEvent,
    ),
  );
}
export function chatTypingIndicatorStoppedEventFromJSON(
  jsonString: string,
): SafeParseResult<ChatTypingIndicatorStoppedEvent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ChatTypingIndicatorStoppedEvent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChatTypingIndicatorStoppedEvent' from JSON`,
  );
}
