/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

/**
 * Service type (iMessage, SMS, RCS, etc.)
 */
export const ChatHandleService = {
  IMessage: "iMessage",
  Sms: "SMS",
  Rcs: "RCS",
} as const;
/**
 * Service type (iMessage, SMS, RCS, etc.)
 */
export type ChatHandleService = OpenEnum<typeof ChatHandleService>;

/**
 * Participant status
 */
export const ChatHandleStatus = {
  Active: "active",
  Left: "left",
  Removed: "removed",
} as const;
/**
 * Participant status
 */
export type ChatHandleStatus = OpenEnum<typeof ChatHandleStatus>;

export type ChatHandle = {
  /**
   * Unique identifier for this handle
   */
  id: string;
  /**
   * Phone number (E.164) or email address of the participant
   */
  handle: string;
  /**
   * Service type (iMessage, SMS, RCS, etc.)
   */
  service: ChatHandleService;
  /**
   * Participant status
   */
  status?: ChatHandleStatus | null | undefined;
  /**
   * When this participant joined the chat
   */
  joinedAt: Date;
  /**
   * When they left (if applicable)
   */
  leftAt?: Date | null | undefined;
  /**
   * Whether this handle belongs to the sender (your phone number)
   */
  isMe?: boolean | null | undefined;
};

/** @internal */
export const ChatHandleService$inboundSchema: z.ZodMiniType<
  ChatHandleService,
  unknown
> = openEnums.inboundSchema(ChatHandleService);
/** @internal */
export const ChatHandleService$outboundSchema: z.ZodMiniType<
  string,
  ChatHandleService
> = openEnums.outboundSchema(ChatHandleService);

/** @internal */
export const ChatHandleStatus$inboundSchema: z.ZodMiniType<
  ChatHandleStatus,
  unknown
> = openEnums.inboundSchema(ChatHandleStatus);
/** @internal */
export const ChatHandleStatus$outboundSchema: z.ZodMiniType<
  string,
  ChatHandleStatus
> = openEnums.outboundSchema(ChatHandleStatus);

/** @internal */
export const ChatHandle$inboundSchema: z.ZodMiniType<ChatHandle, unknown> = z
  .pipe(
    z.object({
      id: types.string(),
      handle: types.string(),
      service: ChatHandleService$inboundSchema,
      status: z.nullable(z._default(ChatHandleStatus$inboundSchema, "active")),
      joined_at: types.date(),
      left_at: z.optional(z.nullable(types.date())),
      is_me: z.optional(z.nullable(types.boolean())),
    }),
    z.transform((v) => {
      return remap$(v, {
        "joined_at": "joinedAt",
        "left_at": "leftAt",
        "is_me": "isMe",
      });
    }),
  );
/** @internal */
export type ChatHandle$Outbound = {
  id: string;
  handle: string;
  service: string;
  status: string | null;
  joined_at: string;
  left_at?: string | null | undefined;
  is_me?: boolean | null | undefined;
};

/** @internal */
export const ChatHandle$outboundSchema: z.ZodMiniType<
  ChatHandle$Outbound,
  ChatHandle
> = z.pipe(
  z.object({
    id: z.string(),
    handle: z.string(),
    service: ChatHandleService$outboundSchema,
    status: z.nullable(z._default(ChatHandleStatus$outboundSchema, "active")),
    joinedAt: z.pipe(z.date(), z.transform(v => v.toISOString())),
    leftAt: z.optional(
      z.nullable(z.pipe(z.date(), z.transform(v => v.toISOString()))),
    ),
    isMe: z.optional(z.nullable(z.boolean())),
  }),
  z.transform((v) => {
    return remap$(v, {
      joinedAt: "joined_at",
      leftAt: "left_at",
      isMe: "is_me",
    });
  }),
);

export function chatHandleToJSON(chatHandle: ChatHandle): string {
  return JSON.stringify(ChatHandle$outboundSchema.parse(chatHandle));
}
export function chatHandleFromJSON(
  jsonString: string,
): SafeParseResult<ChatHandle, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ChatHandle$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChatHandle' from JSON`,
  );
}
