/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import {
  ChatGroupIconUpdatedEvent,
  ChatGroupIconUpdatedEvent$inboundSchema,
  ChatGroupIconUpdatedEvent$Outbound,
  ChatGroupIconUpdatedEvent$outboundSchema,
} from "./chat-group-icon-updated-event.js";
import {
  WebhookEventType,
  WebhookEventType$inboundSchema,
  WebhookEventType$outboundSchema,
} from "./webhook-event-type.js";

/**
 * Complete webhook payload for chat.group_icon_updated events
 */
export type ChatGroupIconUpdatedWebhook = {
  /**
   * API version for the webhook payload format
   */
  apiVersion: string;
  /**
   * Date-based webhook payload version.
   *
   * @remarks
   * Determined by the `?version=` query parameter in your webhook subscription URL.
   * If no version parameter is specified, defaults based on subscription creation date.
   */
  webhookVersion: string;
  /**
   * Valid webhook event types that can be subscribed to
   */
  eventType: WebhookEventType;
  /**
   * Unique identifier for this event (for deduplication)
   */
  eventId: string;
  /**
   * When the event was created
   */
  createdAt: Date;
  /**
   * Trace ID for debugging and correlation across systems.
   */
  traceId: string;
  /**
   * Partner identifier. Present on all webhooks for cross-referencing.
   */
  partnerId: string;
  /**
   * Payload for chat.group_icon_updated webhook events
   */
  data: ChatGroupIconUpdatedEvent;
};

/** @internal */
export const ChatGroupIconUpdatedWebhook$inboundSchema: z.ZodMiniType<
  ChatGroupIconUpdatedWebhook,
  unknown
> = z.pipe(
  z.object({
    api_version: types.string(),
    webhook_version: types.string(),
    event_type: WebhookEventType$inboundSchema,
    event_id: types.string(),
    created_at: types.date(),
    trace_id: types.string(),
    partner_id: types.string(),
    data: ChatGroupIconUpdatedEvent$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "api_version": "apiVersion",
      "webhook_version": "webhookVersion",
      "event_type": "eventType",
      "event_id": "eventId",
      "created_at": "createdAt",
      "trace_id": "traceId",
      "partner_id": "partnerId",
    });
  }),
);
/** @internal */
export type ChatGroupIconUpdatedWebhook$Outbound = {
  api_version: string;
  webhook_version: string;
  event_type: string;
  event_id: string;
  created_at: string;
  trace_id: string;
  partner_id: string;
  data: ChatGroupIconUpdatedEvent$Outbound;
};

/** @internal */
export const ChatGroupIconUpdatedWebhook$outboundSchema: z.ZodMiniType<
  ChatGroupIconUpdatedWebhook$Outbound,
  ChatGroupIconUpdatedWebhook
> = z.pipe(
  z.object({
    apiVersion: z.string(),
    webhookVersion: z.string(),
    eventType: WebhookEventType$outboundSchema,
    eventId: z.string(),
    createdAt: z.pipe(z.date(), z.transform(v => v.toISOString())),
    traceId: z.string(),
    partnerId: z.string(),
    data: ChatGroupIconUpdatedEvent$outboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      apiVersion: "api_version",
      webhookVersion: "webhook_version",
      eventType: "event_type",
      eventId: "event_id",
      createdAt: "created_at",
      traceId: "trace_id",
      partnerId: "partner_id",
    });
  }),
);

export function chatGroupIconUpdatedWebhookToJSON(
  chatGroupIconUpdatedWebhook: ChatGroupIconUpdatedWebhook,
): string {
  return JSON.stringify(
    ChatGroupIconUpdatedWebhook$outboundSchema.parse(
      chatGroupIconUpdatedWebhook,
    ),
  );
}
export function chatGroupIconUpdatedWebhookFromJSON(
  jsonString: string,
): SafeParseResult<ChatGroupIconUpdatedWebhook, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ChatGroupIconUpdatedWebhook$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChatGroupIconUpdatedWebhook' from JSON`,
  );
}
