/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

/**
 * Service type (iMessage, SMS, RCS, etc.)
 */
export const ChatGroupNameUpdatedEventService = {
  IMessage: "iMessage",
  Sms: "SMS",
  Rcs: "RCS",
} as const;
/**
 * Service type (iMessage, SMS, RCS, etc.)
 */
export type ChatGroupNameUpdatedEventService = ClosedEnum<
  typeof ChatGroupNameUpdatedEventService
>;

/**
 * Participant status
 */
export const ChatGroupNameUpdatedEventStatus = {
  Active: "active",
  Left: "left",
  Removed: "removed",
} as const;
/**
 * Participant status
 */
export type ChatGroupNameUpdatedEventStatus = ClosedEnum<
  typeof ChatGroupNameUpdatedEventStatus
>;

/**
 * The handle who made the change.
 */
export type ChatGroupNameUpdatedEventChangedByHandle = {
  /**
   * Unique identifier for this handle
   */
  id: string;
  /**
   * Phone number (E.164) or email address of the participant
   */
  handle: string;
  /**
   * Service type (iMessage, SMS, RCS, etc.)
   */
  service: ChatGroupNameUpdatedEventService;
  /**
   * Participant status
   */
  status?: ChatGroupNameUpdatedEventStatus | null | undefined;
  /**
   * When this participant joined the chat
   */
  joinedAt: Date;
  /**
   * When they left (if applicable)
   */
  leftAt?: Date | null | undefined;
  /**
   * Whether this handle belongs to the sender (your phone number)
   */
  isMe?: boolean | null | undefined;
};

/**
 * Payload for chat.group_name_updated webhook events
 */
export type ChatGroupNameUpdatedEvent = {
  /**
   * Chat identifier (UUID) of the group chat
   */
  chatId: string;
  /**
   * Previous group name (null if no previous name)
   */
  oldValue?: string | null | undefined;
  /**
   * New group name (null if the name was removed)
   */
  newValue?: string | null | undefined;
  /**
   * The handle who made the change.
   */
  changedByHandle?: ChatGroupNameUpdatedEventChangedByHandle | null | undefined;
  /**
   * When the update occurred
   */
  updatedAt: Date;
};

/** @internal */
export const ChatGroupNameUpdatedEventService$inboundSchema: z.ZodMiniEnum<
  typeof ChatGroupNameUpdatedEventService
> = z.enum(ChatGroupNameUpdatedEventService);
/** @internal */
export const ChatGroupNameUpdatedEventService$outboundSchema: z.ZodMiniEnum<
  typeof ChatGroupNameUpdatedEventService
> = ChatGroupNameUpdatedEventService$inboundSchema;

/** @internal */
export const ChatGroupNameUpdatedEventStatus$inboundSchema: z.ZodMiniEnum<
  typeof ChatGroupNameUpdatedEventStatus
> = z.enum(ChatGroupNameUpdatedEventStatus);
/** @internal */
export const ChatGroupNameUpdatedEventStatus$outboundSchema: z.ZodMiniEnum<
  typeof ChatGroupNameUpdatedEventStatus
> = ChatGroupNameUpdatedEventStatus$inboundSchema;

/** @internal */
export const ChatGroupNameUpdatedEventChangedByHandle$inboundSchema:
  z.ZodMiniType<ChatGroupNameUpdatedEventChangedByHandle, unknown> = z.pipe(
    z.object({
      id: types.string(),
      handle: types.string(),
      service: ChatGroupNameUpdatedEventService$inboundSchema,
      status: z.nullable(
        z._default(ChatGroupNameUpdatedEventStatus$inboundSchema, "active"),
      ),
      joined_at: types.date(),
      left_at: z.optional(z.nullable(types.date())),
      is_me: z.optional(z.nullable(types.boolean())),
    }),
    z.transform((v) => {
      return remap$(v, {
        "joined_at": "joinedAt",
        "left_at": "leftAt",
        "is_me": "isMe",
      });
    }),
  );
/** @internal */
export type ChatGroupNameUpdatedEventChangedByHandle$Outbound = {
  id: string;
  handle: string;
  service: string;
  status: string | null;
  joined_at: string;
  left_at?: string | null | undefined;
  is_me?: boolean | null | undefined;
};

/** @internal */
export const ChatGroupNameUpdatedEventChangedByHandle$outboundSchema:
  z.ZodMiniType<
    ChatGroupNameUpdatedEventChangedByHandle$Outbound,
    ChatGroupNameUpdatedEventChangedByHandle
  > = z.pipe(
    z.object({
      id: z.string(),
      handle: z.string(),
      service: ChatGroupNameUpdatedEventService$outboundSchema,
      status: z.nullable(
        z._default(ChatGroupNameUpdatedEventStatus$outboundSchema, "active"),
      ),
      joinedAt: z.pipe(z.date(), z.transform(v => v.toISOString())),
      leftAt: z.optional(
        z.nullable(z.pipe(z.date(), z.transform(v => v.toISOString()))),
      ),
      isMe: z.optional(z.nullable(z.boolean())),
    }),
    z.transform((v) => {
      return remap$(v, {
        joinedAt: "joined_at",
        leftAt: "left_at",
        isMe: "is_me",
      });
    }),
  );

export function chatGroupNameUpdatedEventChangedByHandleToJSON(
  chatGroupNameUpdatedEventChangedByHandle:
    ChatGroupNameUpdatedEventChangedByHandle,
): string {
  return JSON.stringify(
    ChatGroupNameUpdatedEventChangedByHandle$outboundSchema.parse(
      chatGroupNameUpdatedEventChangedByHandle,
    ),
  );
}
export function chatGroupNameUpdatedEventChangedByHandleFromJSON(
  jsonString: string,
): SafeParseResult<
  ChatGroupNameUpdatedEventChangedByHandle,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ChatGroupNameUpdatedEventChangedByHandle$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ChatGroupNameUpdatedEventChangedByHandle' from JSON`,
  );
}

/** @internal */
export const ChatGroupNameUpdatedEvent$inboundSchema: z.ZodMiniType<
  ChatGroupNameUpdatedEvent,
  unknown
> = z.pipe(
  z.object({
    chat_id: types.string(),
    old_value: z.optional(z.nullable(types.string())),
    new_value: z.optional(z.nullable(types.string())),
    changed_by_handle: z.optional(z.nullable(z.lazy(() =>
      ChatGroupNameUpdatedEventChangedByHandle$inboundSchema
    ))),
    updated_at: types.date(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "chat_id": "chatId",
      "old_value": "oldValue",
      "new_value": "newValue",
      "changed_by_handle": "changedByHandle",
      "updated_at": "updatedAt",
    });
  }),
);
/** @internal */
export type ChatGroupNameUpdatedEvent$Outbound = {
  chat_id: string;
  old_value?: string | null | undefined;
  new_value?: string | null | undefined;
  changed_by_handle?:
    | ChatGroupNameUpdatedEventChangedByHandle$Outbound
    | null
    | undefined;
  updated_at: string;
};

/** @internal */
export const ChatGroupNameUpdatedEvent$outboundSchema: z.ZodMiniType<
  ChatGroupNameUpdatedEvent$Outbound,
  ChatGroupNameUpdatedEvent
> = z.pipe(
  z.object({
    chatId: z.string(),
    oldValue: z.optional(z.nullable(z.string())),
    newValue: z.optional(z.nullable(z.string())),
    changedByHandle: z.optional(z.nullable(z.lazy(() =>
      ChatGroupNameUpdatedEventChangedByHandle$outboundSchema
    ))),
    updatedAt: z.pipe(
      z.date(),
      z.transform(v => v.toISOString()),
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      chatId: "chat_id",
      oldValue: "old_value",
      newValue: "new_value",
      changedByHandle: "changed_by_handle",
      updatedAt: "updated_at",
    });
  }),
);

export function chatGroupNameUpdatedEventToJSON(
  chatGroupNameUpdatedEvent: ChatGroupNameUpdatedEvent,
): string {
  return JSON.stringify(
    ChatGroupNameUpdatedEvent$outboundSchema.parse(chatGroupNameUpdatedEvent),
  );
}
export function chatGroupNameUpdatedEventFromJSON(
  jsonString: string,
): SafeParseResult<ChatGroupNameUpdatedEvent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ChatGroupNameUpdatedEvent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChatGroupNameUpdatedEvent' from JSON`,
  );
}
