/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import { ChatHandle, ChatHandle$inboundSchema } from "./chat-handle.js";

export type ChatInfo = {
  /**
   * Chat identifier
   */
  id: string;
  /**
   * Chat participants
   */
  handles: Array<ChatHandle>;
  /**
   * Whether this is a group chat
   */
  isGroup: boolean;
  /**
   * Messaging service
   */
  service: string;
  /**
   * Whether the chat is active
   */
  isActive: boolean;
};

/** @internal */
export const ChatInfo$inboundSchema: z.ZodMiniType<ChatInfo, unknown> = z.pipe(
  z.object({
    id: types.string(),
    handles: z.array(ChatHandle$inboundSchema),
    is_group: types.boolean(),
    service: types.string(),
    is_active: types.boolean(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "is_group": "isGroup",
      "is_active": "isActive",
    });
  }),
);

export function chatInfoFromJSON(
  jsonString: string,
): SafeParseResult<ChatInfo, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ChatInfo$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChatInfo' from JSON`,
  );
}
