/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import {
  WebhookErrorCode,
  WebhookErrorCode$inboundSchema,
  WebhookErrorCode$outboundSchema,
} from "./webhook-error-code.js";

/**
 * Error details for chat.group_name_update_failed webhook events.
 *
 * @remarks
 * See [WebhookErrorCode](#/components/schemas/WebhookErrorCode) for the full error code reference.
 */
export type ChatGroupNameUpdateFailedEvent = {
  /**
   * Chat identifier (UUID) of the group chat
   */
  chatId: string;
  /**
   * Error codes that appear in webhook failure events (`message.failed`,
   *
   * @remarks
   * `chat.group_name_update_failed`, `chat.group_icon_update_failed`).
   *
   * | Code | Name | Description | Recommended Action |
   * |------|------|-------------|-------------------|
   * | 3007 | `retries_exhausted` | Maximum delivery attempts exceeded | Retry after delay |
   * | 4001 | `delivery_failed` | Request could not be delivered | Check phone status |
   */
  errorCode: WebhookErrorCode;
  /**
   * When the failure was detected
   */
  failedAt: Date;
};

/** @internal */
export const ChatGroupNameUpdateFailedEvent$inboundSchema: z.ZodMiniType<
  ChatGroupNameUpdateFailedEvent,
  unknown
> = z.pipe(
  z.object({
    chat_id: types.string(),
    error_code: WebhookErrorCode$inboundSchema,
    failed_at: types.date(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "chat_id": "chatId",
      "error_code": "errorCode",
      "failed_at": "failedAt",
    });
  }),
);
/** @internal */
export type ChatGroupNameUpdateFailedEvent$Outbound = {
  chat_id: string;
  error_code: number;
  failed_at: string;
};

/** @internal */
export const ChatGroupNameUpdateFailedEvent$outboundSchema: z.ZodMiniType<
  ChatGroupNameUpdateFailedEvent$Outbound,
  ChatGroupNameUpdateFailedEvent
> = z.pipe(
  z.object({
    chatId: z.string(),
    errorCode: WebhookErrorCode$outboundSchema,
    failedAt: z.pipe(z.date(), z.transform(v => v.toISOString())),
  }),
  z.transform((v) => {
    return remap$(v, {
      chatId: "chat_id",
      errorCode: "error_code",
      failedAt: "failed_at",
    });
  }),
);

export function chatGroupNameUpdateFailedEventToJSON(
  chatGroupNameUpdateFailedEvent: ChatGroupNameUpdateFailedEvent,
): string {
  return JSON.stringify(
    ChatGroupNameUpdateFailedEvent$outboundSchema.parse(
      chatGroupNameUpdateFailedEvent,
    ),
  );
}
export function chatGroupNameUpdateFailedEventFromJSON(
  jsonString: string,
): SafeParseResult<ChatGroupNameUpdateFailedEvent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ChatGroupNameUpdateFailedEvent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChatGroupNameUpdateFailedEvent' from JSON`,
  );
}
