/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import {
  ChatHandle,
  ChatHandle$inboundSchema,
  ChatHandle$Outbound,
  ChatHandle$outboundSchema,
} from "./chat-handle.js";

/**
 * Service type for the chat
 */
export const ChatCreatedEventService = {
  IMessage: "iMessage",
  Sms: "SMS",
  Rcs: "RCS",
} as const;
/**
 * Service type for the chat
 */
export type ChatCreatedEventService = ClosedEnum<
  typeof ChatCreatedEventService
>;

/**
 * Payload for chat.created webhook events. Matches GET /v3/chats/{chatId} response.
 */
export type ChatCreatedEvent = {
  /**
   * Unique identifier for the chat
   */
  id: string;
  /**
   * Display name for the chat. Defaults to a comma-separated list of recipient handles. Can be updated for group chats.
   */
  displayName: string | null;
  /**
   * Service type for the chat
   */
  service?: ChatCreatedEventService | null | undefined;
  /**
   * List of chat participants with full handle details. Always contains at least two handles (your phone number and the other participant).
   */
  handles: Array<ChatHandle>;
  /**
   * Whether this is a group chat
   */
  isGroup?: boolean | undefined;
  /**
   * When the chat was created
   */
  createdAt: Date;
  /**
   * When the chat was last updated
   */
  updatedAt: Date;
};

/** @internal */
export const ChatCreatedEventService$inboundSchema: z.ZodMiniEnum<
  typeof ChatCreatedEventService
> = z.enum(ChatCreatedEventService);
/** @internal */
export const ChatCreatedEventService$outboundSchema: z.ZodMiniEnum<
  typeof ChatCreatedEventService
> = ChatCreatedEventService$inboundSchema;

/** @internal */
export const ChatCreatedEvent$inboundSchema: z.ZodMiniType<
  ChatCreatedEvent,
  unknown
> = z.pipe(
  z.object({
    id: types.string(),
    display_name: types.nullable(types.string()),
    service: z.optional(z.nullable(ChatCreatedEventService$inboundSchema)),
    handles: z.array(ChatHandle$inboundSchema),
    is_group: z._default(types.boolean(), false),
    created_at: types.date(),
    updated_at: types.date(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "display_name": "displayName",
      "is_group": "isGroup",
      "created_at": "createdAt",
      "updated_at": "updatedAt",
    });
  }),
);
/** @internal */
export type ChatCreatedEvent$Outbound = {
  id: string;
  display_name: string | null;
  service?: string | null | undefined;
  handles: Array<ChatHandle$Outbound>;
  is_group: boolean;
  created_at: string;
  updated_at: string;
};

/** @internal */
export const ChatCreatedEvent$outboundSchema: z.ZodMiniType<
  ChatCreatedEvent$Outbound,
  ChatCreatedEvent
> = z.pipe(
  z.object({
    id: z.string(),
    displayName: z.nullable(z.string()),
    service: z.optional(z.nullable(ChatCreatedEventService$outboundSchema)),
    handles: z.array(ChatHandle$outboundSchema),
    isGroup: z._default(z.boolean(), false),
    createdAt: z.pipe(z.date(), z.transform(v => v.toISOString())),
    updatedAt: z.pipe(z.date(), z.transform(v => v.toISOString())),
  }),
  z.transform((v) => {
    return remap$(v, {
      displayName: "display_name",
      isGroup: "is_group",
      createdAt: "created_at",
      updatedAt: "updated_at",
    });
  }),
);

export function chatCreatedEventToJSON(
  chatCreatedEvent: ChatCreatedEvent,
): string {
  return JSON.stringify(
    ChatCreatedEvent$outboundSchema.parse(chatCreatedEvent),
  );
}
export function chatCreatedEventFromJSON(
  jsonString: string,
): SafeParseResult<ChatCreatedEvent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ChatCreatedEvent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChatCreatedEvent' from JSON`,
  );
}
