/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

/**
 * Service type (iMessage, SMS, RCS, etc.)
 */
export const ChatGroupIconUpdatedEventService = {
  IMessage: "iMessage",
  Sms: "SMS",
  Rcs: "RCS",
} as const;
/**
 * Service type (iMessage, SMS, RCS, etc.)
 */
export type ChatGroupIconUpdatedEventService = ClosedEnum<
  typeof ChatGroupIconUpdatedEventService
>;

/**
 * Participant status
 */
export const ChatGroupIconUpdatedEventStatus = {
  Active: "active",
  Left: "left",
  Removed: "removed",
} as const;
/**
 * Participant status
 */
export type ChatGroupIconUpdatedEventStatus = ClosedEnum<
  typeof ChatGroupIconUpdatedEventStatus
>;

/**
 * The handle who made the change.
 */
export type ChatGroupIconUpdatedEventChangedByHandle = {
  /**
   * Unique identifier for this handle
   */
  id: string;
  /**
   * Phone number (E.164) or email address of the participant
   */
  handle: string;
  /**
   * Service type (iMessage, SMS, RCS, etc.)
   */
  service: ChatGroupIconUpdatedEventService;
  /**
   * Participant status
   */
  status?: ChatGroupIconUpdatedEventStatus | null | undefined;
  /**
   * When this participant joined the chat
   */
  joinedAt: Date;
  /**
   * When they left (if applicable)
   */
  leftAt?: Date | null | undefined;
  /**
   * Whether this handle belongs to the sender (your phone number)
   */
  isMe?: boolean | null | undefined;
};

/**
 * Payload for chat.group_icon_updated webhook events
 */
export type ChatGroupIconUpdatedEvent = {
  /**
   * Chat identifier (UUID) of the group chat
   */
  chatId: string;
  /**
   * Previous icon URL (null if no previous icon)
   */
  oldValue?: string | null | undefined;
  /**
   * New icon URL (null if the icon was removed)
   */
  newValue?: string | null | undefined;
  /**
   * The handle who made the change.
   */
  changedByHandle?: ChatGroupIconUpdatedEventChangedByHandle | null | undefined;
  /**
   * When the update occurred
   */
  updatedAt: Date;
};

/** @internal */
export const ChatGroupIconUpdatedEventService$inboundSchema: z.ZodMiniEnum<
  typeof ChatGroupIconUpdatedEventService
> = z.enum(ChatGroupIconUpdatedEventService);
/** @internal */
export const ChatGroupIconUpdatedEventService$outboundSchema: z.ZodMiniEnum<
  typeof ChatGroupIconUpdatedEventService
> = ChatGroupIconUpdatedEventService$inboundSchema;

/** @internal */
export const ChatGroupIconUpdatedEventStatus$inboundSchema: z.ZodMiniEnum<
  typeof ChatGroupIconUpdatedEventStatus
> = z.enum(ChatGroupIconUpdatedEventStatus);
/** @internal */
export const ChatGroupIconUpdatedEventStatus$outboundSchema: z.ZodMiniEnum<
  typeof ChatGroupIconUpdatedEventStatus
> = ChatGroupIconUpdatedEventStatus$inboundSchema;

/** @internal */
export const ChatGroupIconUpdatedEventChangedByHandle$inboundSchema:
  z.ZodMiniType<ChatGroupIconUpdatedEventChangedByHandle, unknown> = z.pipe(
    z.object({
      id: types.string(),
      handle: types.string(),
      service: ChatGroupIconUpdatedEventService$inboundSchema,
      status: z.nullable(
        z._default(ChatGroupIconUpdatedEventStatus$inboundSchema, "active"),
      ),
      joined_at: types.date(),
      left_at: z.optional(z.nullable(types.date())),
      is_me: z.optional(z.nullable(types.boolean())),
    }),
    z.transform((v) => {
      return remap$(v, {
        "joined_at": "joinedAt",
        "left_at": "leftAt",
        "is_me": "isMe",
      });
    }),
  );
/** @internal */
export type ChatGroupIconUpdatedEventChangedByHandle$Outbound = {
  id: string;
  handle: string;
  service: string;
  status: string | null;
  joined_at: string;
  left_at?: string | null | undefined;
  is_me?: boolean | null | undefined;
};

/** @internal */
export const ChatGroupIconUpdatedEventChangedByHandle$outboundSchema:
  z.ZodMiniType<
    ChatGroupIconUpdatedEventChangedByHandle$Outbound,
    ChatGroupIconUpdatedEventChangedByHandle
  > = z.pipe(
    z.object({
      id: z.string(),
      handle: z.string(),
      service: ChatGroupIconUpdatedEventService$outboundSchema,
      status: z.nullable(
        z._default(ChatGroupIconUpdatedEventStatus$outboundSchema, "active"),
      ),
      joinedAt: z.pipe(z.date(), z.transform(v => v.toISOString())),
      leftAt: z.optional(
        z.nullable(z.pipe(z.date(), z.transform(v => v.toISOString()))),
      ),
      isMe: z.optional(z.nullable(z.boolean())),
    }),
    z.transform((v) => {
      return remap$(v, {
        joinedAt: "joined_at",
        leftAt: "left_at",
        isMe: "is_me",
      });
    }),
  );

export function chatGroupIconUpdatedEventChangedByHandleToJSON(
  chatGroupIconUpdatedEventChangedByHandle:
    ChatGroupIconUpdatedEventChangedByHandle,
): string {
  return JSON.stringify(
    ChatGroupIconUpdatedEventChangedByHandle$outboundSchema.parse(
      chatGroupIconUpdatedEventChangedByHandle,
    ),
  );
}
export function chatGroupIconUpdatedEventChangedByHandleFromJSON(
  jsonString: string,
): SafeParseResult<
  ChatGroupIconUpdatedEventChangedByHandle,
  SDKValidationError
> {
  return safeParse(
    jsonString,
    (x) =>
      ChatGroupIconUpdatedEventChangedByHandle$inboundSchema.parse(
        JSON.parse(x),
      ),
    `Failed to parse 'ChatGroupIconUpdatedEventChangedByHandle' from JSON`,
  );
}

/** @internal */
export const ChatGroupIconUpdatedEvent$inboundSchema: z.ZodMiniType<
  ChatGroupIconUpdatedEvent,
  unknown
> = z.pipe(
  z.object({
    chat_id: types.string(),
    old_value: z.optional(z.nullable(types.string())),
    new_value: z.optional(z.nullable(types.string())),
    changed_by_handle: z.optional(z.nullable(z.lazy(() =>
      ChatGroupIconUpdatedEventChangedByHandle$inboundSchema
    ))),
    updated_at: types.date(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "chat_id": "chatId",
      "old_value": "oldValue",
      "new_value": "newValue",
      "changed_by_handle": "changedByHandle",
      "updated_at": "updatedAt",
    });
  }),
);
/** @internal */
export type ChatGroupIconUpdatedEvent$Outbound = {
  chat_id: string;
  old_value?: string | null | undefined;
  new_value?: string | null | undefined;
  changed_by_handle?:
    | ChatGroupIconUpdatedEventChangedByHandle$Outbound
    | null
    | undefined;
  updated_at: string;
};

/** @internal */
export const ChatGroupIconUpdatedEvent$outboundSchema: z.ZodMiniType<
  ChatGroupIconUpdatedEvent$Outbound,
  ChatGroupIconUpdatedEvent
> = z.pipe(
  z.object({
    chatId: z.string(),
    oldValue: z.optional(z.nullable(z.string())),
    newValue: z.optional(z.nullable(z.string())),
    changedByHandle: z.optional(z.nullable(z.lazy(() =>
      ChatGroupIconUpdatedEventChangedByHandle$outboundSchema
    ))),
    updatedAt: z.pipe(
      z.date(),
      z.transform(v => v.toISOString()),
    ),
  }),
  z.transform((v) => {
    return remap$(v, {
      chatId: "chat_id",
      oldValue: "old_value",
      newValue: "new_value",
      changedByHandle: "changed_by_handle",
      updatedAt: "updated_at",
    });
  }),
);

export function chatGroupIconUpdatedEventToJSON(
  chatGroupIconUpdatedEvent: ChatGroupIconUpdatedEvent,
): string {
  return JSON.stringify(
    ChatGroupIconUpdatedEvent$outboundSchema.parse(chatGroupIconUpdatedEvent),
  );
}
export function chatGroupIconUpdatedEventFromJSON(
  jsonString: string,
): SafeParseResult<ChatGroupIconUpdatedEvent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ChatGroupIconUpdatedEvent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ChatGroupIconUpdatedEvent' from JSON`,
  );
}
