/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import { ChatHandle, ChatHandle$inboundSchema } from "./chat-handle.js";

/**
 * Service type for the chat
 */
export const ChatService = {
  IMessage: "iMessage",
  Sms: "SMS",
  Rcs: "RCS",
} as const;
/**
 * Service type for the chat
 */
export type ChatService = OpenEnum<typeof ChatService>;

export type Chat = {
  /**
   * Unique identifier for the chat
   */
  id: string;
  /**
   * Display name for the chat. Defaults to a comma-separated list of recipient handles. Can be updated for group chats.
   */
  displayName: string | null;
  /**
   * Service type for the chat
   */
  service?: ChatService | null | undefined;
  /**
   * List of chat participants with full handle details. Always contains at least two handles (your phone number and the other participant).
   */
  handles: Array<ChatHandle>;
  /**
   * Whether the chat is archived
   */
  isArchived: boolean;
  /**
   * Whether this is a group chat
   */
  isGroup: boolean;
  /**
   * When the chat was created
   */
  createdAt: Date;
  /**
   * When the chat was last updated
   */
  updatedAt: Date;
};

/** @internal */
export const ChatService$inboundSchema: z.ZodMiniType<ChatService, unknown> =
  openEnums.inboundSchema(ChatService);

/** @internal */
export const Chat$inboundSchema: z.ZodMiniType<Chat, unknown> = z.pipe(
  z.object({
    id: types.string(),
    display_name: types.nullable(types.string()),
    service: z.optional(z.nullable(ChatService$inboundSchema)),
    handles: z.array(ChatHandle$inboundSchema),
    is_archived: z._default(types.boolean(), false),
    is_group: z._default(types.boolean(), false),
    created_at: types.date(),
    updated_at: types.date(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "display_name": "displayName",
      "is_archived": "isArchived",
      "is_group": "isGroup",
      "created_at": "createdAt",
      "updated_at": "updatedAt",
    });
  }),
);

export function chatFromJSON(
  jsonString: string,
): SafeParseResult<Chat, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Chat$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Chat' from JSON`,
  );
}
