/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import {
  MessageContent,
  MessageContent$Outbound,
  MessageContent$outboundSchema,
} from "./message-content.js";

export type CreateChatRequest = {
  /**
   * Sender phone number in E.164 format. Must be a phone number that the
   *
   * @remarks
   * authenticated partner has permission to send from.
   */
  from: string;
  /**
   * Array of recipient handles (phone numbers in E.164 format or email addresses).
   *
   * @remarks
   * For individual chats, provide one recipient. For group chats, provide multiple.
   */
  to: Array<string>;
  /**
   * Message content container. Groups all message-related fields together,
   *
   * @remarks
   * separating the "what" (message content) from the "where" (routing fields like from/to).
   */
  message: MessageContent;
};

/** @internal */
export type CreateChatRequest$Outbound = {
  from: string;
  to: Array<string>;
  message: MessageContent$Outbound;
};

/** @internal */
export const CreateChatRequest$outboundSchema: z.ZodMiniType<
  CreateChatRequest$Outbound,
  CreateChatRequest
> = z.object({
  from: z.string(),
  to: z.array(z.string()),
  message: MessageContent$outboundSchema,
});

export function createChatRequestToJSON(
  createChatRequest: CreateChatRequest,
): string {
  return JSON.stringify(
    CreateChatRequest$outboundSchema.parse(createChatRequest),
  );
}
