/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import {
  WebhookEventType,
  WebhookEventType$outboundSchema,
} from "./webhook-event-type.js";

export type CreateWebhookSubscriptionRequest = {
  /**
   * URL where webhook events will be sent. Must be HTTPS.
   */
  targetUrl: string;
  /**
   * List of event types to subscribe to
   */
  subscribedEvents: Array<WebhookEventType>;
};

/** @internal */
export type CreateWebhookSubscriptionRequest$Outbound = {
  target_url: string;
  subscribed_events: Array<string>;
};

/** @internal */
export const CreateWebhookSubscriptionRequest$outboundSchema: z.ZodMiniType<
  CreateWebhookSubscriptionRequest$Outbound,
  CreateWebhookSubscriptionRequest
> = z.pipe(
  z.object({
    targetUrl: z.string(),
    subscribedEvents: z.array(WebhookEventType$outboundSchema),
  }),
  z.transform((v) => {
    return remap$(v, {
      targetUrl: "target_url",
      subscribedEvents: "subscribed_events",
    });
  }),
);

export function createWebhookSubscriptionRequestToJSON(
  createWebhookSubscriptionRequest: CreateWebhookSubscriptionRequest,
): string {
  return JSON.stringify(
    CreateWebhookSubscriptionRequest$outboundSchema.parse(
      createWebhookSubscriptionRequest,
    ),
  );
}
