/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type DeleteMessageRequest = {
  /**
   * ID of the chat containing the message to delete
   */
  chatId: string;
};

/** @internal */
export type DeleteMessageRequest$Outbound = {
  chat_id: string;
};

/** @internal */
export const DeleteMessageRequest$outboundSchema: z.ZodMiniType<
  DeleteMessageRequest$Outbound,
  DeleteMessageRequest
> = z.pipe(
  z.object({
    chatId: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      chatId: "chat_id",
    });
  }),
);

export function deleteMessageRequestToJSON(
  deleteMessageRequest: DeleteMessageRequest,
): string {
  return JSON.stringify(
    DeleteMessageRequest$outboundSchema.parse(deleteMessageRequest),
  );
}
