/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

/**
 * Current delivery status of a message
 */
export const DeliveryStatus = {
  Pending: "pending",
  Queued: "queued",
  Sent: "sent",
  Delivered: "delivered",
  Failed: "failed",
} as const;
/**
 * Current delivery status of a message
 */
export type DeliveryStatus = OpenEnum<typeof DeliveryStatus>;

/** @internal */
export const DeliveryStatus$inboundSchema: z.ZodMiniType<
  DeliveryStatus,
  unknown
> = openEnums.inboundSchema(DeliveryStatus);
