/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import { Message, Message$inboundSchema } from "./message.js";

/**
 * Response containing messages in a thread with pagination
 */
export type GetThreadResponse = {
  /**
   * Messages in the thread, ordered by the specified order parameter
   */
  messages: Array<Message>;
  /**
   * Cursor for fetching the next page of results (null if no more results)
   */
  nextCursor?: string | null | undefined;
};

/** @internal */
export const GetThreadResponse$inboundSchema: z.ZodMiniType<
  GetThreadResponse,
  unknown
> = z.pipe(
  z.object({
    messages: z.array(Message$inboundSchema),
    next_cursor: z.optional(z.nullable(types.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "next_cursor": "nextCursor",
    });
  }),
);

export function getThreadResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetThreadResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetThreadResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetThreadResponse' from JSON`,
  );
}
