/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type MediaPart = {
  /**
   * Indicates this is a media attachment part
   */
  type: "media";
  /**
   * Any publicly accessible HTTPS URL to the media file. The server downloads and
   *
   * @remarks
   * sends the file automatically — no pre-upload step required.
   *
   * **Size limit:** 10MB maximum for URL-based downloads. For larger files (up to 100MB),
   * use the pre-upload flow: `POST /v3/attachments` to get a presigned URL, upload directly,
   * then reference by `attachment_id`.
   *
   * **Requirements:**
   * - URL must include a supported file extension (e.g., `.jpg`, `.pdf`)
   * - Server's Content-Type header must match the URL extension
   *
   * **Supported formats:**
   * - Images: .jpg, .jpeg, .png, .gif, .heic, .heif, .tif, .tiff, .bmp
   * - Videos: .mp4, .mov, .m4v, .mpeg, .mpg, .3gp
   * - Documents: .pdf, .txt, .rtf, .csv, .doc, .docx, .xls, .xlsx, .ppt, .pptx, .pages, .numbers, .key, .epub, .zip, .html, .htm
   * - Contact & Calendar: .vcf, .ics
   *
   * **Note:** Audio files should use the dedicated `/v3/chats/{chatId}/voicememo` endpoint.
   * For repeated sends of the same file, use `attachment_id` to avoid redundant downloads.
   *
   * Either `url` or `attachment_id` must be provided, but not both.
   */
  url?: string | undefined;
  /**
   * Reference to a file pre-uploaded via `POST /v3/attachments` (optional).
   *
   * @remarks
   * The file is already stored, so sends using this ID skip the download step —
   * useful when sending the same file to many recipients.
   *
   * Either `url` or `attachment_id` must be provided, but not both.
   */
  attachmentId?: string | undefined;
  /**
   * Optional idempotency key for this specific message part.
   *
   * @remarks
   * Use this to prevent duplicate sends of the same part.
   */
  idempotencyKey?: string | undefined;
};

/** @internal */
export type MediaPart$Outbound = {
  type: "media";
  url?: string | undefined;
  attachment_id?: string | undefined;
  idempotency_key?: string | undefined;
};

/** @internal */
export const MediaPart$outboundSchema: z.ZodMiniType<
  MediaPart$Outbound,
  MediaPart
> = z.pipe(
  z.object({
    type: z.literal("media"),
    url: z.optional(z.string()),
    attachmentId: z.optional(z.string()),
    idempotencyKey: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      attachmentId: "attachment_id",
      idempotencyKey: "idempotency_key",
    });
  }),
);

export function mediaPartToJSON(mediaPart: MediaPart): string {
  return JSON.stringify(MediaPart$outboundSchema.parse(mediaPart));
}
