/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import { Reaction, Reaction$inboundSchema } from "./reaction.js";

/**
 * A media attachment part
 */
export type MediaPartResponse = {
  /**
   * Indicates this is a media attachment part
   */
  type: "media";
  /**
   * Unique attachment identifier
   */
  id: string;
  /**
   * Presigned URL for downloading the attachment (expires in 1 hour).
   *
   * @remarks
   */
  url: string;
  /**
   * Original filename
   */
  filename: string;
  /**
   * MIME type of the file
   */
  mimeType: string;
  /**
   * File size in bytes
   */
  sizeBytes: number;
  /**
   * Reactions on this message part
   */
  reactions: Array<Reaction> | null;
};

/** @internal */
export const MediaPartResponse$inboundSchema: z.ZodMiniType<
  MediaPartResponse,
  unknown
> = z.pipe(
  z.object({
    type: types.literal("media"),
    id: types.string(),
    url: types.string(),
    filename: types.string(),
    mime_type: types.string(),
    size_bytes: types.number(),
    reactions: types.nullable(z.array(Reaction$inboundSchema)),
  }),
  z.transform((v) => {
    return remap$(v, {
      "mime_type": "mimeType",
      "size_bytes": "sizeBytes",
    });
  }),
);

export function mediaPartResponseFromJSON(
  jsonString: string,
): SafeParseResult<MediaPartResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MediaPartResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MediaPartResponse' from JSON`,
  );
}
