/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import {
  MediaPart,
  MediaPart$Outbound,
  MediaPart$outboundSchema,
} from "./media-part.js";
import {
  TextPart,
  TextPart$Outbound,
  TextPart$outboundSchema,
} from "./text-part.js";

export type MessagePart = TextPart | MediaPart;

/** @internal */
export type MessagePart$Outbound = TextPart$Outbound | MediaPart$Outbound;

/** @internal */
export const MessagePart$outboundSchema: z.ZodMiniType<
  MessagePart$Outbound,
  MessagePart
> = z.union([TextPart$outboundSchema, MediaPart$outboundSchema]);

export function messagePartToJSON(messagePart: MessagePart): string {
  return JSON.stringify(MessagePart$outboundSchema.parse(messagePart));
}
