/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Type of effect
 */
export const MessageEffectType = {
  Screen: "screen",
  Bubble: "bubble",
} as const;
/**
 * Type of effect
 */
export type MessageEffectType = ClosedEnum<typeof MessageEffectType>;

/**
 * iMessage effect applied to a message (screen or bubble effect)
 */
export type MessageEffect = {
  /**
   * Type of effect
   */
  type?: MessageEffectType | undefined;
  /**
   * Name of the effect. Common values:
   *
   * @remarks
   * - Screen effects: confetti, fireworks, lasers, sparkles, celebration, hearts, love, balloons, happy_birthday, echo, spotlight
   * - Bubble effects: slam, loud, gentle, invisible
   */
  name?: string | undefined;
};

/** @internal */
export const MessageEffectType$outboundSchema: z.ZodMiniEnum<
  typeof MessageEffectType
> = z.enum(MessageEffectType);

/** @internal */
export type MessageEffect$Outbound = {
  type?: string | undefined;
  name?: string | undefined;
};

/** @internal */
export const MessageEffect$outboundSchema: z.ZodMiniType<
  MessageEffect$Outbound,
  MessageEffect
> = z.object({
  type: z.optional(MessageEffectType$outboundSchema),
  name: z.optional(z.string()),
});

export function messageEffectToJSON(messageEffect: MessageEffect): string {
  return JSON.stringify(MessageEffect$outboundSchema.parse(messageEffect));
}
