/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import {
  WebhookErrorCode,
  WebhookErrorCode$inboundSchema,
  WebhookErrorCode$outboundSchema,
} from "./webhook-error-code.js";

/**
 * Error details for message.failed webhook events.
 *
 * @remarks
 * See [WebhookErrorCode](#/components/schemas/WebhookErrorCode) for the full error code reference.
 */
export type MessageFailedEvent = {
  /**
   * Chat identifier (UUID)
   */
  chatId?: string | undefined;
  /**
   * Message identifier (UUID)
   */
  messageId?: string | undefined;
  /**
   * Error codes that appear in webhook failure events (`message.failed`,
   *
   * @remarks
   * `chat.group_name_update_failed`, `chat.group_icon_update_failed`).
   *
   * | Code | Name | Description | Recommended Action |
   * |------|------|-------------|-------------------|
   * | 3007 | `retries_exhausted` | Maximum delivery attempts exceeded | Retry after delay |
   * | 4001 | `delivery_failed` | Request could not be delivered | Check phone status |
   */
  code: WebhookErrorCode;
  /**
   * Human-readable description of the failure
   */
  reason?: string | undefined;
  /**
   * When the failure was detected
   */
  failedAt: Date;
};

/** @internal */
export const MessageFailedEvent$inboundSchema: z.ZodMiniType<
  MessageFailedEvent,
  unknown
> = z.pipe(
  z.object({
    chat_id: types.optional(types.string()),
    message_id: types.optional(types.string()),
    code: WebhookErrorCode$inboundSchema,
    reason: types.optional(types.string()),
    failed_at: types.date(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "chat_id": "chatId",
      "message_id": "messageId",
      "failed_at": "failedAt",
    });
  }),
);
/** @internal */
export type MessageFailedEvent$Outbound = {
  chat_id?: string | undefined;
  message_id?: string | undefined;
  code: number;
  reason?: string | undefined;
  failed_at: string;
};

/** @internal */
export const MessageFailedEvent$outboundSchema: z.ZodMiniType<
  MessageFailedEvent$Outbound,
  MessageFailedEvent
> = z.pipe(
  z.object({
    chatId: z.optional(z.string()),
    messageId: z.optional(z.string()),
    code: WebhookErrorCode$outboundSchema,
    reason: z.optional(z.string()),
    failedAt: z.pipe(z.date(), z.transform(v => v.toISOString())),
  }),
  z.transform((v) => {
    return remap$(v, {
      chatId: "chat_id",
      messageId: "message_id",
      failedAt: "failed_at",
    });
  }),
);

export function messageFailedEventToJSON(
  messageFailedEvent: MessageFailedEvent,
): string {
  return JSON.stringify(
    MessageFailedEvent$outboundSchema.parse(messageFailedEvent),
  );
}
export function messageFailedEventFromJSON(
  jsonString: string,
): SafeParseResult<MessageFailedEvent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => MessageFailedEvent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'MessageFailedEvent' from JSON`,
  );
}
