/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

/**
 * Service type (iMessage, SMS, RCS, etc.)
 */
export const ParticipantRemovedEventService = {
  IMessage: "iMessage",
  Sms: "SMS",
  Rcs: "RCS",
} as const;
/**
 * Service type (iMessage, SMS, RCS, etc.)
 */
export type ParticipantRemovedEventService = ClosedEnum<
  typeof ParticipantRemovedEventService
>;

/**
 * Participant status
 */
export const ParticipantRemovedEventStatus = {
  Active: "active",
  Left: "left",
  Removed: "removed",
} as const;
/**
 * Participant status
 */
export type ParticipantRemovedEventStatus = ClosedEnum<
  typeof ParticipantRemovedEventStatus
>;

/**
 * The removed participant as a full handle object
 */
export type ParticipantRemovedEventParticipant = {
  /**
   * Unique identifier for this handle
   */
  id: string;
  /**
   * Phone number (E.164) or email address of the participant
   */
  handle: string;
  /**
   * Service type (iMessage, SMS, RCS, etc.)
   */
  service: ParticipantRemovedEventService;
  /**
   * Participant status
   */
  status?: ParticipantRemovedEventStatus | null | undefined;
  /**
   * When this participant joined the chat
   */
  joinedAt: Date;
  /**
   * When they left (if applicable)
   */
  leftAt?: Date | null | undefined;
  /**
   * Whether this handle belongs to the sender (your phone number)
   */
  isMe?: boolean | null | undefined;
};

/**
 * Payload for participant.removed webhook events
 */
export type ParticipantRemovedEvent = {
  /**
   * Chat identifier (UUID) of the group chat
   */
  chatId?: string | undefined;
  /**
   * DEPRECATED: Use participant instead. Handle (phone number or email address) of the removed participant.
   *
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  handle: string;
  /**
   * The removed participant as a full handle object
   */
  participant?: ParticipantRemovedEventParticipant | undefined;
  /**
   * When the participant was removed
   */
  removedAt?: Date | undefined;
};

/** @internal */
export const ParticipantRemovedEventService$inboundSchema: z.ZodMiniEnum<
  typeof ParticipantRemovedEventService
> = z.enum(ParticipantRemovedEventService);
/** @internal */
export const ParticipantRemovedEventService$outboundSchema: z.ZodMiniEnum<
  typeof ParticipantRemovedEventService
> = ParticipantRemovedEventService$inboundSchema;

/** @internal */
export const ParticipantRemovedEventStatus$inboundSchema: z.ZodMiniEnum<
  typeof ParticipantRemovedEventStatus
> = z.enum(ParticipantRemovedEventStatus);
/** @internal */
export const ParticipantRemovedEventStatus$outboundSchema: z.ZodMiniEnum<
  typeof ParticipantRemovedEventStatus
> = ParticipantRemovedEventStatus$inboundSchema;

/** @internal */
export const ParticipantRemovedEventParticipant$inboundSchema: z.ZodMiniType<
  ParticipantRemovedEventParticipant,
  unknown
> = z.pipe(
  z.object({
    id: types.string(),
    handle: types.string(),
    service: ParticipantRemovedEventService$inboundSchema,
    status: z.nullable(
      z._default(ParticipantRemovedEventStatus$inboundSchema, "active"),
    ),
    joined_at: types.date(),
    left_at: z.optional(z.nullable(types.date())),
    is_me: z.optional(z.nullable(types.boolean())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "joined_at": "joinedAt",
      "left_at": "leftAt",
      "is_me": "isMe",
    });
  }),
);
/** @internal */
export type ParticipantRemovedEventParticipant$Outbound = {
  id: string;
  handle: string;
  service: string;
  status: string | null;
  joined_at: string;
  left_at?: string | null | undefined;
  is_me?: boolean | null | undefined;
};

/** @internal */
export const ParticipantRemovedEventParticipant$outboundSchema: z.ZodMiniType<
  ParticipantRemovedEventParticipant$Outbound,
  ParticipantRemovedEventParticipant
> = z.pipe(
  z.object({
    id: z.string(),
    handle: z.string(),
    service: ParticipantRemovedEventService$outboundSchema,
    status: z.nullable(
      z._default(ParticipantRemovedEventStatus$outboundSchema, "active"),
    ),
    joinedAt: z.pipe(z.date(), z.transform(v => v.toISOString())),
    leftAt: z.optional(
      z.nullable(z.pipe(z.date(), z.transform(v => v.toISOString()))),
    ),
    isMe: z.optional(z.nullable(z.boolean())),
  }),
  z.transform((v) => {
    return remap$(v, {
      joinedAt: "joined_at",
      leftAt: "left_at",
      isMe: "is_me",
    });
  }),
);

export function participantRemovedEventParticipantToJSON(
  participantRemovedEventParticipant: ParticipantRemovedEventParticipant,
): string {
  return JSON.stringify(
    ParticipantRemovedEventParticipant$outboundSchema.parse(
      participantRemovedEventParticipant,
    ),
  );
}
export function participantRemovedEventParticipantFromJSON(
  jsonString: string,
): SafeParseResult<ParticipantRemovedEventParticipant, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      ParticipantRemovedEventParticipant$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ParticipantRemovedEventParticipant' from JSON`,
  );
}

/** @internal */
export const ParticipantRemovedEvent$inboundSchema: z.ZodMiniType<
  ParticipantRemovedEvent,
  unknown
> = z.pipe(
  z.object({
    chat_id: types.optional(types.string()),
    handle: types.string(),
    participant: types.optional(
      z.lazy(() => ParticipantRemovedEventParticipant$inboundSchema),
    ),
    removed_at: types.optional(types.date()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "chat_id": "chatId",
      "removed_at": "removedAt",
    });
  }),
);
/** @internal */
export type ParticipantRemovedEvent$Outbound = {
  chat_id?: string | undefined;
  handle: string;
  participant?: ParticipantRemovedEventParticipant$Outbound | undefined;
  removed_at?: string | undefined;
};

/** @internal */
export const ParticipantRemovedEvent$outboundSchema: z.ZodMiniType<
  ParticipantRemovedEvent$Outbound,
  ParticipantRemovedEvent
> = z.pipe(
  z.object({
    chatId: z.optional(z.string()),
    handle: z.string(),
    participant: z.optional(
      z.lazy(() => ParticipantRemovedEventParticipant$outboundSchema),
    ),
    removedAt: z.optional(z.pipe(z.date(), z.transform(v => v.toISOString()))),
  }),
  z.transform((v) => {
    return remap$(v, {
      chatId: "chat_id",
      removedAt: "removed_at",
    });
  }),
);

export function participantRemovedEventToJSON(
  participantRemovedEvent: ParticipantRemovedEvent,
): string {
  return JSON.stringify(
    ParticipantRemovedEvent$outboundSchema.parse(participantRemovedEvent),
  );
}
export function participantRemovedEventFromJSON(
  jsonString: string,
): SafeParseResult<ParticipantRemovedEvent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ParticipantRemovedEvent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ParticipantRemovedEvent' from JSON`,
  );
}
