/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

/**
 * Service type (iMessage, SMS, RCS, etc.)
 */
export const ParticipantAddedEventService = {
  IMessage: "iMessage",
  Sms: "SMS",
  Rcs: "RCS",
} as const;
/**
 * Service type (iMessage, SMS, RCS, etc.)
 */
export type ParticipantAddedEventService = ClosedEnum<
  typeof ParticipantAddedEventService
>;

/**
 * Participant status
 */
export const ParticipantAddedEventStatus = {
  Active: "active",
  Left: "left",
  Removed: "removed",
} as const;
/**
 * Participant status
 */
export type ParticipantAddedEventStatus = ClosedEnum<
  typeof ParticipantAddedEventStatus
>;

/**
 * The added participant as a full handle object
 */
export type ParticipantAddedEventParticipant = {
  /**
   * Unique identifier for this handle
   */
  id: string;
  /**
   * Phone number (E.164) or email address of the participant
   */
  handle: string;
  /**
   * Service type (iMessage, SMS, RCS, etc.)
   */
  service: ParticipantAddedEventService;
  /**
   * Participant status
   */
  status?: ParticipantAddedEventStatus | null | undefined;
  /**
   * When this participant joined the chat
   */
  joinedAt: Date;
  /**
   * When they left (if applicable)
   */
  leftAt?: Date | null | undefined;
  /**
   * Whether this handle belongs to the sender (your phone number)
   */
  isMe?: boolean | null | undefined;
};

/**
 * Payload for participant.added webhook events
 */
export type ParticipantAddedEvent = {
  /**
   * Chat identifier (UUID) of the group chat
   */
  chatId?: string | undefined;
  /**
   * DEPRECATED: Use participant instead. Handle (phone number or email address) of the added participant.
   *
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  handle: string;
  /**
   * The added participant as a full handle object
   */
  participant?: ParticipantAddedEventParticipant | undefined;
  /**
   * When the participant was added
   */
  addedAt?: Date | undefined;
};

/** @internal */
export const ParticipantAddedEventService$inboundSchema: z.ZodMiniEnum<
  typeof ParticipantAddedEventService
> = z.enum(ParticipantAddedEventService);
/** @internal */
export const ParticipantAddedEventService$outboundSchema: z.ZodMiniEnum<
  typeof ParticipantAddedEventService
> = ParticipantAddedEventService$inboundSchema;

/** @internal */
export const ParticipantAddedEventStatus$inboundSchema: z.ZodMiniEnum<
  typeof ParticipantAddedEventStatus
> = z.enum(ParticipantAddedEventStatus);
/** @internal */
export const ParticipantAddedEventStatus$outboundSchema: z.ZodMiniEnum<
  typeof ParticipantAddedEventStatus
> = ParticipantAddedEventStatus$inboundSchema;

/** @internal */
export const ParticipantAddedEventParticipant$inboundSchema: z.ZodMiniType<
  ParticipantAddedEventParticipant,
  unknown
> = z.pipe(
  z.object({
    id: types.string(),
    handle: types.string(),
    service: ParticipantAddedEventService$inboundSchema,
    status: z.nullable(
      z._default(ParticipantAddedEventStatus$inboundSchema, "active"),
    ),
    joined_at: types.date(),
    left_at: z.optional(z.nullable(types.date())),
    is_me: z.optional(z.nullable(types.boolean())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "joined_at": "joinedAt",
      "left_at": "leftAt",
      "is_me": "isMe",
    });
  }),
);
/** @internal */
export type ParticipantAddedEventParticipant$Outbound = {
  id: string;
  handle: string;
  service: string;
  status: string | null;
  joined_at: string;
  left_at?: string | null | undefined;
  is_me?: boolean | null | undefined;
};

/** @internal */
export const ParticipantAddedEventParticipant$outboundSchema: z.ZodMiniType<
  ParticipantAddedEventParticipant$Outbound,
  ParticipantAddedEventParticipant
> = z.pipe(
  z.object({
    id: z.string(),
    handle: z.string(),
    service: ParticipantAddedEventService$outboundSchema,
    status: z.nullable(
      z._default(ParticipantAddedEventStatus$outboundSchema, "active"),
    ),
    joinedAt: z.pipe(z.date(), z.transform(v => v.toISOString())),
    leftAt: z.optional(
      z.nullable(z.pipe(z.date(), z.transform(v => v.toISOString()))),
    ),
    isMe: z.optional(z.nullable(z.boolean())),
  }),
  z.transform((v) => {
    return remap$(v, {
      joinedAt: "joined_at",
      leftAt: "left_at",
      isMe: "is_me",
    });
  }),
);

export function participantAddedEventParticipantToJSON(
  participantAddedEventParticipant: ParticipantAddedEventParticipant,
): string {
  return JSON.stringify(
    ParticipantAddedEventParticipant$outboundSchema.parse(
      participantAddedEventParticipant,
    ),
  );
}
export function participantAddedEventParticipantFromJSON(
  jsonString: string,
): SafeParseResult<ParticipantAddedEventParticipant, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ParticipantAddedEventParticipant$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ParticipantAddedEventParticipant' from JSON`,
  );
}

/** @internal */
export const ParticipantAddedEvent$inboundSchema: z.ZodMiniType<
  ParticipantAddedEvent,
  unknown
> = z.pipe(
  z.object({
    chat_id: types.optional(types.string()),
    handle: types.string(),
    participant: types.optional(
      z.lazy(() => ParticipantAddedEventParticipant$inboundSchema),
    ),
    added_at: types.optional(types.date()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "chat_id": "chatId",
      "added_at": "addedAt",
    });
  }),
);
/** @internal */
export type ParticipantAddedEvent$Outbound = {
  chat_id?: string | undefined;
  handle: string;
  participant?: ParticipantAddedEventParticipant$Outbound | undefined;
  added_at?: string | undefined;
};

/** @internal */
export const ParticipantAddedEvent$outboundSchema: z.ZodMiniType<
  ParticipantAddedEvent$Outbound,
  ParticipantAddedEvent
> = z.pipe(
  z.object({
    chatId: z.optional(z.string()),
    handle: z.string(),
    participant: z.optional(
      z.lazy(() => ParticipantAddedEventParticipant$outboundSchema),
    ),
    addedAt: z.optional(z.pipe(z.date(), z.transform(v => v.toISOString()))),
  }),
  z.transform((v) => {
    return remap$(v, {
      chatId: "chat_id",
      addedAt: "added_at",
    });
  }),
);

export function participantAddedEventToJSON(
  participantAddedEvent: ParticipantAddedEvent,
): string {
  return JSON.stringify(
    ParticipantAddedEvent$outboundSchema.parse(participantAddedEvent),
  );
}
export function participantAddedEventFromJSON(
  jsonString: string,
): SafeParseResult<ParticipantAddedEvent, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ParticipantAddedEvent$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ParticipantAddedEvent' from JSON`,
  );
}
