/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import {
  PhoneCapabilities,
  PhoneCapabilities$inboundSchema,
} from "./phone-capabilities.js";

/**
 * Type of phone number
 */
export const PhoneNumberInfoType = {
  Twilio: "TWILIO",
  AppleId: "APPLE_ID",
} as const;
/**
 * Type of phone number
 */
export type PhoneNumberInfoType = OpenEnum<typeof PhoneNumberInfoType>;

export type PhoneNumberInfo = {
  /**
   * Unique identifier for the phone number
   */
  id: string;
  /**
   * Phone number in E.164 format
   */
  phoneNumber: string;
  /**
   * Type of phone number
   */
  type: PhoneNumberInfoType;
  /**
   * ISO 3166-1 alpha-2 country code
   */
  countryCode: string;
  capabilities: PhoneCapabilities;
};

/** @internal */
export const PhoneNumberInfoType$inboundSchema: z.ZodMiniType<
  PhoneNumberInfoType,
  unknown
> = openEnums.inboundSchema(PhoneNumberInfoType);

/** @internal */
export const PhoneNumberInfo$inboundSchema: z.ZodMiniType<
  PhoneNumberInfo,
  unknown
> = z.pipe(
  z.object({
    id: types.string(),
    phone_number: types.string(),
    type: PhoneNumberInfoType$inboundSchema,
    country_code: types.string(),
    capabilities: PhoneCapabilities$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "phone_number": "phoneNumber",
      "country_code": "countryCode",
    });
  }),
);

export function phoneNumberInfoFromJSON(
  jsonString: string,
): SafeParseResult<PhoneNumberInfo, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PhoneNumberInfo$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PhoneNumberInfo' from JSON`,
  );
}
