/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type PhoneCapabilities = {
  /**
   * Whether SMS messaging is supported
   */
  sms: boolean;
  /**
   * Whether MMS messaging is supported
   */
  mms: boolean;
  /**
   * Whether voice calls are supported
   */
  voice: boolean;
};

/** @internal */
export const PhoneCapabilities$inboundSchema: z.ZodMiniType<
  PhoneCapabilities,
  unknown
> = z.object({
  sms: types.boolean(),
  mms: types.boolean(),
  voice: types.boolean(),
});

export function phoneCapabilitiesFromJSON(
  jsonString: string,
): SafeParseResult<PhoneCapabilities, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PhoneCapabilities$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PhoneCapabilities' from JSON`,
  );
}
