/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

/**
 * Type of reaction. Standard iMessage tapbacks are love, like, dislike, laugh, emphasize, question.
 *
 * @remarks
 * Custom emoji reactions have type "custom" with the actual emoji in the custom_emoji field.
 */
export const ReactionType = {
  Love: "love",
  Like: "like",
  Dislike: "dislike",
  Laugh: "laugh",
  Emphasize: "emphasize",
  Question: "question",
  Custom: "custom",
} as const;
/**
 * Type of reaction. Standard iMessage tapbacks are love, like, dislike, laugh, emphasize, question.
 *
 * @remarks
 * Custom emoji reactions have type "custom" with the actual emoji in the custom_emoji field.
 */
export type ReactionType = OpenEnum<typeof ReactionType>;

/** @internal */
export const ReactionType$inboundSchema: z.ZodMiniType<ReactionType, unknown> =
  openEnums.inboundSchema(ReactionType);
/** @internal */
export const ReactionType$outboundSchema: z.ZodMiniType<string, ReactionType> =
  openEnums.outboundSchema(ReactionType);
