/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import { ChatHandle, ChatHandle$inboundSchema } from "./chat-handle.js";
import { ReactionType, ReactionType$inboundSchema } from "./reaction-type.js";

export type Reaction = {
  /**
   * Whether this reaction is from the current user
   */
  isMe: boolean;
  handle: ChatHandle;
  /**
   * Type of reaction. Standard iMessage tapbacks are love, like, dislike, laugh, emphasize, question.
   *
   * @remarks
   * Custom emoji reactions have type "custom" with the actual emoji in the custom_emoji field.
   */
  type: ReactionType;
  /**
   * Custom emoji if type is "custom", null otherwise
   */
  customEmoji?: string | null | undefined;
};

/** @internal */
export const Reaction$inboundSchema: z.ZodMiniType<Reaction, unknown> = z.pipe(
  z.object({
    is_me: types.boolean(),
    handle: ChatHandle$inboundSchema,
    type: ReactionType$inboundSchema,
    custom_emoji: z.optional(z.nullable(types.string())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "is_me": "isMe",
      "custom_emoji": "customEmoji",
    });
  }),
);

export function reactionFromJSON(
  jsonString: string,
): SafeParseResult<Reaction, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => Reaction$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'Reaction' from JSON`,
  );
}
