/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import {
  ReactionType,
  ReactionType$inboundSchema,
  ReactionType$outboundSchema,
} from "./reaction-type.js";

/**
 * Service type (iMessage, SMS, RCS, etc.)
 */
export const ReactionEventBaseFromHandleService = {
  IMessage: "iMessage",
  Sms: "SMS",
  Rcs: "RCS",
} as const;
/**
 * Service type (iMessage, SMS, RCS, etc.)
 */
export type ReactionEventBaseFromHandleService = ClosedEnum<
  typeof ReactionEventBaseFromHandleService
>;

/**
 * Participant status
 */
export const ReactionEventBaseStatus = {
  Active: "active",
  Left: "left",
  Removed: "removed",
} as const;
/**
 * Participant status
 */
export type ReactionEventBaseStatus = ClosedEnum<
  typeof ReactionEventBaseStatus
>;

/**
 * The person who added/removed the reaction as a full handle object
 */
export type ReactionEventBaseFromHandle = {
  /**
   * Unique identifier for this handle
   */
  id: string;
  /**
   * Phone number (E.164) or email address of the participant
   */
  handle: string;
  /**
   * Service type (iMessage, SMS, RCS, etc.)
   */
  service: ReactionEventBaseFromHandleService;
  /**
   * Participant status
   */
  status?: ReactionEventBaseStatus | null | undefined;
  /**
   * When this participant joined the chat
   */
  joinedAt: Date;
  /**
   * When they left (if applicable)
   */
  leftAt?: Date | null | undefined;
  /**
   * Whether this handle belongs to the sender (your phone number)
   */
  isMe?: boolean | null | undefined;
};

/**
 * Message service type
 */
export const ReactionEventBaseService = {
  IMessage: "iMessage",
  Sms: "SMS",
  Rcs: "RCS",
} as const;
/**
 * Message service type
 */
export type ReactionEventBaseService = ClosedEnum<
  typeof ReactionEventBaseService
>;

export type ReactionEventBase = {
  /**
   * Chat identifier (UUID)
   */
  chatId?: string | undefined;
  /**
   * DEPRECATED: Use from_handle instead. Phone number or email address of the person who added/removed the reaction.
   *
   * @deprecated field: This will be removed in a future release, please migrate away from it as soon as possible.
   */
  from?: string | undefined;
  /**
   * The person who added/removed the reaction as a full handle object
   */
  fromHandle?: ReactionEventBaseFromHandle | undefined;
  /**
   * Message identifier (UUID) that the reaction was added to or removed from
   */
  messageId?: string | undefined;
  /**
   * Index of the message part that was reacted to (0-based)
   */
  partIndex?: number | undefined;
  /**
   * Type of reaction. Standard iMessage tapbacks are love, like, dislike, laugh, emphasize, question.
   *
   * @remarks
   * Custom emoji reactions have type "custom" with the actual emoji in the custom_emoji field.
   */
  reactionType: ReactionType;
  /**
   * The actual emoji when reaction_type is "custom". Null for standard tapbacks.
   */
  customEmoji?: string | null | undefined;
  /**
   * Whether this reaction was from the owner of the phone number (true) or from someone else (false)
   */
  isFromMe: boolean;
  /**
   * Message service type
   */
  service?: ReactionEventBaseService | undefined;
  /**
   * When the reaction was added or removed
   */
  reactedAt?: Date | undefined;
};

/** @internal */
export const ReactionEventBaseFromHandleService$inboundSchema: z.ZodMiniEnum<
  typeof ReactionEventBaseFromHandleService
> = z.enum(ReactionEventBaseFromHandleService);
/** @internal */
export const ReactionEventBaseFromHandleService$outboundSchema: z.ZodMiniEnum<
  typeof ReactionEventBaseFromHandleService
> = ReactionEventBaseFromHandleService$inboundSchema;

/** @internal */
export const ReactionEventBaseStatus$inboundSchema: z.ZodMiniEnum<
  typeof ReactionEventBaseStatus
> = z.enum(ReactionEventBaseStatus);
/** @internal */
export const ReactionEventBaseStatus$outboundSchema: z.ZodMiniEnum<
  typeof ReactionEventBaseStatus
> = ReactionEventBaseStatus$inboundSchema;

/** @internal */
export const ReactionEventBaseFromHandle$inboundSchema: z.ZodMiniType<
  ReactionEventBaseFromHandle,
  unknown
> = z.pipe(
  z.object({
    id: types.string(),
    handle: types.string(),
    service: ReactionEventBaseFromHandleService$inboundSchema,
    status: z.nullable(
      z._default(ReactionEventBaseStatus$inboundSchema, "active"),
    ),
    joined_at: types.date(),
    left_at: z.optional(z.nullable(types.date())),
    is_me: z.optional(z.nullable(types.boolean())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "joined_at": "joinedAt",
      "left_at": "leftAt",
      "is_me": "isMe",
    });
  }),
);
/** @internal */
export type ReactionEventBaseFromHandle$Outbound = {
  id: string;
  handle: string;
  service: string;
  status: string | null;
  joined_at: string;
  left_at?: string | null | undefined;
  is_me?: boolean | null | undefined;
};

/** @internal */
export const ReactionEventBaseFromHandle$outboundSchema: z.ZodMiniType<
  ReactionEventBaseFromHandle$Outbound,
  ReactionEventBaseFromHandle
> = z.pipe(
  z.object({
    id: z.string(),
    handle: z.string(),
    service: ReactionEventBaseFromHandleService$outboundSchema,
    status: z.nullable(
      z._default(ReactionEventBaseStatus$outboundSchema, "active"),
    ),
    joinedAt: z.pipe(z.date(), z.transform(v => v.toISOString())),
    leftAt: z.optional(
      z.nullable(z.pipe(z.date(), z.transform(v => v.toISOString()))),
    ),
    isMe: z.optional(z.nullable(z.boolean())),
  }),
  z.transform((v) => {
    return remap$(v, {
      joinedAt: "joined_at",
      leftAt: "left_at",
      isMe: "is_me",
    });
  }),
);

export function reactionEventBaseFromHandleToJSON(
  reactionEventBaseFromHandle: ReactionEventBaseFromHandle,
): string {
  return JSON.stringify(
    ReactionEventBaseFromHandle$outboundSchema.parse(
      reactionEventBaseFromHandle,
    ),
  );
}
export function reactionEventBaseFromHandleFromJSON(
  jsonString: string,
): SafeParseResult<ReactionEventBaseFromHandle, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ReactionEventBaseFromHandle$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ReactionEventBaseFromHandle' from JSON`,
  );
}

/** @internal */
export const ReactionEventBaseService$inboundSchema: z.ZodMiniEnum<
  typeof ReactionEventBaseService
> = z.enum(ReactionEventBaseService);
/** @internal */
export const ReactionEventBaseService$outboundSchema: z.ZodMiniEnum<
  typeof ReactionEventBaseService
> = ReactionEventBaseService$inboundSchema;

/** @internal */
export const ReactionEventBase$inboundSchema: z.ZodMiniType<
  ReactionEventBase,
  unknown
> = z.pipe(
  z.object({
    chat_id: types.optional(types.string()),
    from: types.optional(types.string()),
    from_handle: types.optional(
      z.lazy(() => ReactionEventBaseFromHandle$inboundSchema),
    ),
    message_id: types.optional(types.string()),
    part_index: types.optional(types.number()),
    reaction_type: ReactionType$inboundSchema,
    custom_emoji: z.optional(z.nullable(types.string())),
    is_from_me: types.boolean(),
    service: types.optional(ReactionEventBaseService$inboundSchema),
    reacted_at: types.optional(types.date()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "chat_id": "chatId",
      "from_handle": "fromHandle",
      "message_id": "messageId",
      "part_index": "partIndex",
      "reaction_type": "reactionType",
      "custom_emoji": "customEmoji",
      "is_from_me": "isFromMe",
      "reacted_at": "reactedAt",
    });
  }),
);
/** @internal */
export type ReactionEventBase$Outbound = {
  chat_id?: string | undefined;
  from?: string | undefined;
  from_handle?: ReactionEventBaseFromHandle$Outbound | undefined;
  message_id?: string | undefined;
  part_index?: number | undefined;
  reaction_type: string;
  custom_emoji?: string | null | undefined;
  is_from_me: boolean;
  service?: string | undefined;
  reacted_at?: string | undefined;
};

/** @internal */
export const ReactionEventBase$outboundSchema: z.ZodMiniType<
  ReactionEventBase$Outbound,
  ReactionEventBase
> = z.pipe(
  z.object({
    chatId: z.optional(z.string()),
    from: z.optional(z.string()),
    fromHandle: z.optional(
      z.lazy(() => ReactionEventBaseFromHandle$outboundSchema),
    ),
    messageId: z.optional(z.string()),
    partIndex: z.optional(z.int()),
    reactionType: ReactionType$outboundSchema,
    customEmoji: z.optional(z.nullable(z.string())),
    isFromMe: z.boolean(),
    service: z.optional(ReactionEventBaseService$outboundSchema),
    reactedAt: z.optional(z.pipe(z.date(), z.transform(v => v.toISOString()))),
  }),
  z.transform((v) => {
    return remap$(v, {
      chatId: "chat_id",
      fromHandle: "from_handle",
      messageId: "message_id",
      partIndex: "part_index",
      reactionType: "reaction_type",
      customEmoji: "custom_emoji",
      isFromMe: "is_from_me",
      reactedAt: "reacted_at",
    });
  }),
);

export function reactionEventBaseToJSON(
  reactionEventBase: ReactionEventBase,
): string {
  return JSON.stringify(
    ReactionEventBase$outboundSchema.parse(reactionEventBase),
  );
}
export function reactionEventBaseFromJSON(
  jsonString: string,
): SafeParseResult<ReactionEventBase, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ReactionEventBase$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ReactionEventBase' from JSON`,
  );
}
