/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type RemoveParticipantRequest = {
  /**
   * Phone number (E.164 format) or email address of the participant to remove
   */
  handle: string;
};

/** @internal */
export type RemoveParticipantRequest$Outbound = {
  handle: string;
};

/** @internal */
export const RemoveParticipantRequest$outboundSchema: z.ZodMiniType<
  RemoveParticipantRequest$Outbound,
  RemoveParticipantRequest
> = z.object({
  handle: z.string(),
});

export function removeParticipantRequestToJSON(
  removeParticipantRequest: RemoveParticipantRequest,
): string {
  return JSON.stringify(
    RemoveParticipantRequest$outboundSchema.parse(removeParticipantRequest),
  );
}
