/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

/**
 * Indicates this message is a threaded reply to another message
 */
export type ReplyTo = {
  /**
   * The ID of the message to reply to
   */
  messageId: string;
  /**
   * The specific message part to reply to (0-based index).
   *
   * @remarks
   * Defaults to 0 (first part) if not provided.
   * Use this when replying to a specific part of a multipart message.
   */
  partIndex?: number | undefined;
};

/** @internal */
export type ReplyTo$Outbound = {
  message_id: string;
  part_index?: number | undefined;
};

/** @internal */
export const ReplyTo$outboundSchema: z.ZodMiniType<ReplyTo$Outbound, ReplyTo> =
  z.pipe(
    z.object({
      messageId: z.string(),
      partIndex: z.optional(z.int()),
    }),
    z.transform((v) => {
      return remap$(v, {
        messageId: "message_id",
        partIndex: "part_index",
      });
    }),
  );

export function replyToToJSON(replyTo: ReplyTo): string {
  return JSON.stringify(ReplyTo$outboundSchema.parse(replyTo));
}
