/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import {
  SupportedContentType,
  SupportedContentType$outboundSchema,
} from "./supported-content-type.js";

export type RequestUploadRequest = {
  /**
   * Name of the file to upload
   */
  filename: string;
  /**
   * Supported MIME types for file attachments and media URLs.
   *
   * @remarks
   *
   * **Images:** image/jpeg, image/png, image/gif, image/heic, image/heif, image/tiff, image/bmp
   *
   * **Videos:** video/mp4, video/quicktime, video/mpeg, video/3gpp
   *
   * **Audio:** audio/mpeg, audio/mp4, audio/x-m4a, audio/x-caf, audio/wav, audio/aiff, audio/aac, audio/amr
   *
   * **Documents:** application/pdf, text/plain, text/vcard, text/rtf, text/csv, text/html, text/calendar, application/msword, application/vnd.openxmlformats-officedocument.wordprocessingml.document, application/vnd.ms-excel, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-powerpoint, application/vnd.openxmlformats-officedocument.presentationml.presentation, application/vnd.apple.pages, application/vnd.apple.numbers, application/vnd.apple.keynote, application/epub+zip, application/zip
   *
   * **Unsupported:** WebP, SVG, FLAC, OGG, and executable files are explicitly rejected.
   */
  contentType: SupportedContentType;
  /**
   * Size of the file in bytes (max 100MB)
   */
  sizeBytes: number;
};

/** @internal */
export type RequestUploadRequest$Outbound = {
  filename: string;
  content_type: string;
  size_bytes: number;
};

/** @internal */
export const RequestUploadRequest$outboundSchema: z.ZodMiniType<
  RequestUploadRequest$Outbound,
  RequestUploadRequest
> = z.pipe(
  z.object({
    filename: z.string(),
    contentType: SupportedContentType$outboundSchema,
    sizeBytes: z.int(),
  }),
  z.transform((v) => {
    return remap$(v, {
      contentType: "content_type",
      sizeBytes: "size_bytes",
    });
  }),
);

export function requestUploadRequestToJSON(
  requestUploadRequest: RequestUploadRequest,
): string {
  return JSON.stringify(
    RequestUploadRequest$outboundSchema.parse(requestUploadRequest),
  );
}
