/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

/**
 * A media attachment part
 */
export type SchemasMediaPartResponse = {
  /**
   * Indicates this is a media attachment part
   */
  type: "media";
  /**
   * Unique attachment identifier
   */
  id: string;
  /**
   * Presigned URL for downloading the attachment (expires in 1 hour).
   *
   * @remarks
   */
  url: string;
  /**
   * Original filename
   */
  filename: string;
  /**
   * MIME type of the file
   */
  mimeType: string;
  /**
   * File size in bytes
   */
  sizeBytes: number;
};

/** @internal */
export const SchemasMediaPartResponse$inboundSchema: z.ZodMiniType<
  SchemasMediaPartResponse,
  unknown
> = z.pipe(
  z.object({
    type: types.literal("media"),
    id: types.string(),
    url: types.string(),
    filename: types.string(),
    mime_type: types.string(),
    size_bytes: types.number(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "mime_type": "mimeType",
      "size_bytes": "sizeBytes",
    });
  }),
);
/** @internal */
export type SchemasMediaPartResponse$Outbound = {
  type: "media";
  id: string;
  url: string;
  filename: string;
  mime_type: string;
  size_bytes: number;
};

/** @internal */
export const SchemasMediaPartResponse$outboundSchema: z.ZodMiniType<
  SchemasMediaPartResponse$Outbound,
  SchemasMediaPartResponse
> = z.pipe(
  z.object({
    type: z.literal("media"),
    id: z.string(),
    url: z.string(),
    filename: z.string(),
    mimeType: z.string(),
    sizeBytes: z.int(),
  }),
  z.transform((v) => {
    return remap$(v, {
      mimeType: "mime_type",
      sizeBytes: "size_bytes",
    });
  }),
);

export function schemasMediaPartResponseToJSON(
  schemasMediaPartResponse: SchemasMediaPartResponse,
): string {
  return JSON.stringify(
    SchemasMediaPartResponse$outboundSchema.parse(schemasMediaPartResponse),
  );
}
export function schemasMediaPartResponseFromJSON(
  jsonString: string,
): SafeParseResult<SchemasMediaPartResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SchemasMediaPartResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SchemasMediaPartResponse' from JSON`,
  );
}
