/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

/**
 * A text message part
 */
export type SchemasTextPartResponse = {
  /**
   * Indicates this is a text message part
   */
  type: "text";
  /**
   * The text content
   */
  value: string;
};

/** @internal */
export const SchemasTextPartResponse$inboundSchema: z.ZodMiniType<
  SchemasTextPartResponse,
  unknown
> = z.object({
  type: types.literal("text"),
  value: types.string(),
});
/** @internal */
export type SchemasTextPartResponse$Outbound = {
  type: "text";
  value: string;
};

/** @internal */
export const SchemasTextPartResponse$outboundSchema: z.ZodMiniType<
  SchemasTextPartResponse$Outbound,
  SchemasTextPartResponse
> = z.object({
  type: z.literal("text"),
  value: z.string(),
});

export function schemasTextPartResponseToJSON(
  schemasTextPartResponse: SchemasTextPartResponse,
): string {
  return JSON.stringify(
    SchemasTextPartResponse$outboundSchema.parse(schemasTextPartResponse),
  );
}
export function schemasTextPartResponseFromJSON(
  jsonString: string,
): SafeParseResult<SchemasTextPartResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SchemasTextPartResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SchemasTextPartResponse' from JSON`,
  );
}
