/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import { SentMessage, SentMessage$inboundSchema } from "./sent-message.js";

/**
 * Response for sending a message to a chat
 */
export type SendMessageResponse = {
  /**
   * Unique identifier of the chat this message was sent to
   */
  chatId: string;
  /**
   * A message that was sent (used in CreateChat and SendMessage responses)
   */
  message: SentMessage;
};

/** @internal */
export const SendMessageResponse$inboundSchema: z.ZodMiniType<
  SendMessageResponse,
  unknown
> = z.pipe(
  z.object({
    chat_id: types.string(),
    message: SentMessage$inboundSchema,
  }),
  z.transform((v) => {
    return remap$(v, {
      "chat_id": "chatId",
    });
  }),
);

export function sendMessageResponseFromJSON(
  jsonString: string,
): SafeParseResult<SendMessageResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SendMessageResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SendMessageResponse' from JSON`,
  );
}
