/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { ClosedEnum } from "../../types/enums.js";
import { ReactionType, ReactionType$outboundSchema } from "./reaction-type.js";

/**
 * Whether to add or remove the reaction
 */
export const Operation = {
  Add: "add",
  Remove: "remove",
} as const;
/**
 * Whether to add or remove the reaction
 */
export type Operation = ClosedEnum<typeof Operation>;

export type SendReactionRequest = {
  /**
   * Whether to add or remove the reaction
   */
  operation: Operation;
  /**
   * Type of reaction. Standard iMessage tapbacks are love, like, dislike, laugh, emphasize, question.
   *
   * @remarks
   * Custom emoji reactions have type "custom" with the actual emoji in the custom_emoji field.
   */
  type: ReactionType;
  /**
   * Custom emoji string. Required when type is "custom".
   *
   * @remarks
   */
  customEmoji?: string | undefined;
  /**
   * Optional index of the message part to react to.
   *
   * @remarks
   * If not provided, reacts to the entire message (part 0).
   */
  partIndex?: number | undefined;
};

/** @internal */
export const Operation$outboundSchema: z.ZodMiniEnum<typeof Operation> = z.enum(
  Operation,
);

/** @internal */
export type SendReactionRequest$Outbound = {
  operation: string;
  type: string;
  custom_emoji?: string | undefined;
  part_index?: number | undefined;
};

/** @internal */
export const SendReactionRequest$outboundSchema: z.ZodMiniType<
  SendReactionRequest$Outbound,
  SendReactionRequest
> = z.pipe(
  z.object({
    operation: Operation$outboundSchema,
    type: ReactionType$outboundSchema,
    customEmoji: z.optional(z.string()),
    partIndex: z.optional(z.int()),
  }),
  z.transform((v) => {
    return remap$(v, {
      customEmoji: "custom_emoji",
      partIndex: "part_index",
    });
  }),
);

export function sendReactionRequestToJSON(
  sendReactionRequest: SendReactionRequest,
): string {
  return JSON.stringify(
    SendReactionRequest$outboundSchema.parse(sendReactionRequest),
  );
}
