/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import {
  MessageContent,
  MessageContent$Outbound,
  MessageContent$outboundSchema,
} from "./message-content.js";

export type SendMessageToChatRequest = {
  /**
   * Message content container. Groups all message-related fields together,
   *
   * @remarks
   * separating the "what" (message content) from the "where" (routing fields like from/to).
   */
  message: MessageContent;
};

/** @internal */
export type SendMessageToChatRequest$Outbound = {
  message: MessageContent$Outbound;
};

/** @internal */
export const SendMessageToChatRequest$outboundSchema: z.ZodMiniType<
  SendMessageToChatRequest$Outbound,
  SendMessageToChatRequest
> = z.object({
  message: MessageContent$outboundSchema,
});

export function sendMessageToChatRequestToJSON(
  sendMessageToChatRequest: SendMessageToChatRequest,
): string {
  return JSON.stringify(
    SendMessageToChatRequest$outboundSchema.parse(sendMessageToChatRequest),
  );
}
