/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

/**
 * Request to send a voice memo to a chat (chat_id provided in path)
 */
export type SendVoiceMemoToChatRequest = {
  /**
   * Sender phone number in E.164 format
   */
  from: string;
  /**
   * URL of the voice memo audio file. Must be a publicly accessible HTTPS URL.
   */
  voiceMemoUrl: string;
};

/** @internal */
export type SendVoiceMemoToChatRequest$Outbound = {
  from: string;
  voice_memo_url: string;
};

/** @internal */
export const SendVoiceMemoToChatRequest$outboundSchema: z.ZodMiniType<
  SendVoiceMemoToChatRequest$Outbound,
  SendVoiceMemoToChatRequest
> = z.pipe(
  z.object({
    from: z.string(),
    voiceMemoUrl: z.string(),
  }),
  z.transform((v) => {
    return remap$(v, {
      voiceMemoUrl: "voice_memo_url",
    });
  }),
);

export function sendVoiceMemoToChatRequestToJSON(
  sendVoiceMemoToChatRequest: SendVoiceMemoToChatRequest,
): string {
  return JSON.stringify(
    SendVoiceMemoToChatRequest$outboundSchema.parse(sendVoiceMemoToChatRequest),
  );
}
