/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

/**
 * Supported MIME types for file attachments and media URLs.
 *
 * @remarks
 *
 * **Images:** image/jpeg, image/png, image/gif, image/heic, image/heif, image/tiff, image/bmp
 *
 * **Videos:** video/mp4, video/quicktime, video/mpeg, video/3gpp
 *
 * **Audio:** audio/mpeg, audio/mp4, audio/x-m4a, audio/x-caf, audio/wav, audio/aiff, audio/aac, audio/amr
 *
 * **Documents:** application/pdf, text/plain, text/vcard, text/rtf, text/csv, text/html, text/calendar, application/msword, application/vnd.openxmlformats-officedocument.wordprocessingml.document, application/vnd.ms-excel, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-powerpoint, application/vnd.openxmlformats-officedocument.presentationml.presentation, application/vnd.apple.pages, application/vnd.apple.numbers, application/vnd.apple.keynote, application/epub+zip, application/zip
 *
 * **Unsupported:** WebP, SVG, FLAC, OGG, and executable files are explicitly rejected.
 */
export const SupportedContentType = {
  ImageJpeg: "image/jpeg",
  ImageJpg: "image/jpg",
  ImagePng: "image/png",
  ImageGif: "image/gif",
  ImageHeic: "image/heic",
  ImageHeif: "image/heif",
  ImageTiff: "image/tiff",
  ImageBmp: "image/bmp",
  ImageXMsBmp: "image/x-ms-bmp",
  VideoMp4: "video/mp4",
  VideoQuicktime: "video/quicktime",
  VideoMpeg: "video/mpeg",
  VideoXM4v: "video/x-m4v",
  Video3gpp: "video/3gpp",
  AudioMpeg: "audio/mpeg",
  AudioMp3: "audio/mp3",
  AudioMp4: "audio/mp4",
  AudioXM4a: "audio/x-m4a",
  AudioM4a: "audio/m4a",
  AudioXCaf: "audio/x-caf",
  AudioWav: "audio/wav",
  AudioXWav: "audio/x-wav",
  AudioAiff: "audio/aiff",
  AudioXAiff: "audio/x-aiff",
  AudioAac: "audio/aac",
  AudioXAac: "audio/x-aac",
  AudioAmr: "audio/amr",
  ApplicationPdf: "application/pdf",
  TextPlain: "text/plain",
  TextVcard: "text/vcard",
  TextXVcard: "text/x-vcard",
  TextRtf: "text/rtf",
  ApplicationRtf: "application/rtf",
  TextCsv: "text/csv",
  TextHtml: "text/html",
  TextCalendar: "text/calendar",
  ApplicationMsword: "application/msword",
  ApplicationVndOpenxmlformatsOfficedocumentWordprocessingmlDocument:
    "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  ApplicationVndMsExcel: "application/vnd.ms-excel",
  ApplicationVndOpenxmlformatsOfficedocumentSpreadsheetmlSheet:
    "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  ApplicationVndMsPowerpoint: "application/vnd.ms-powerpoint",
  ApplicationVndOpenxmlformatsOfficedocumentPresentationmlPresentation:
    "application/vnd.openxmlformats-officedocument.presentationml.presentation",
  ApplicationVndApplePages: "application/vnd.apple.pages",
  ApplicationXIworkPagesSffpages: "application/x-iwork-pages-sffpages",
  ApplicationVndAppleNumbers: "application/vnd.apple.numbers",
  ApplicationXIworkNumbersSffnumbers: "application/x-iwork-numbers-sffnumbers",
  ApplicationVndAppleKeynote: "application/vnd.apple.keynote",
  ApplicationXIworkKeynoteSffkey: "application/x-iwork-keynote-sffkey",
  ApplicationEpubPlusZip: "application/epub+zip",
  ApplicationZip: "application/zip",
  ApplicationXZipCompressed: "application/x-zip-compressed",
} as const;
/**
 * Supported MIME types for file attachments and media URLs.
 *
 * @remarks
 *
 * **Images:** image/jpeg, image/png, image/gif, image/heic, image/heif, image/tiff, image/bmp
 *
 * **Videos:** video/mp4, video/quicktime, video/mpeg, video/3gpp
 *
 * **Audio:** audio/mpeg, audio/mp4, audio/x-m4a, audio/x-caf, audio/wav, audio/aiff, audio/aac, audio/amr
 *
 * **Documents:** application/pdf, text/plain, text/vcard, text/rtf, text/csv, text/html, text/calendar, application/msword, application/vnd.openxmlformats-officedocument.wordprocessingml.document, application/vnd.ms-excel, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet, application/vnd.ms-powerpoint, application/vnd.openxmlformats-officedocument.presentationml.presentation, application/vnd.apple.pages, application/vnd.apple.numbers, application/vnd.apple.keynote, application/epub+zip, application/zip
 *
 * **Unsupported:** WebP, SVG, FLAC, OGG, and executable files are explicitly rejected.
 */
export type SupportedContentType = OpenEnum<typeof SupportedContentType>;

/** @internal */
export const SupportedContentType$inboundSchema: z.ZodMiniType<
  SupportedContentType,
  unknown
> = openEnums.inboundSchema(SupportedContentType);
/** @internal */
export const SupportedContentType$outboundSchema: z.ZodMiniType<
  string,
  SupportedContentType
> = openEnums.outboundSchema(SupportedContentType);
