/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type TextPart = {
  /**
   * Indicates this is a text message part
   */
  type: "text";
  /**
   * The text content
   */
  value: string;
  /**
   * Optional idempotency key for this specific message part.
   *
   * @remarks
   * Use this to prevent duplicate sends of the same part.
   */
  idempotencyKey?: string | undefined;
};

/** @internal */
export type TextPart$Outbound = {
  type: "text";
  value: string;
  idempotency_key?: string | undefined;
};

/** @internal */
export const TextPart$outboundSchema: z.ZodMiniType<
  TextPart$Outbound,
  TextPart
> = z.pipe(
  z.object({
    type: z.literal("text"),
    value: z.string(),
    idempotencyKey: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      idempotencyKey: "idempotency_key",
    });
  }),
);

export function textPartToJSON(textPart: TextPart): string {
  return JSON.stringify(TextPart$outboundSchema.parse(textPart));
}
