/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import { Reaction, Reaction$inboundSchema } from "./reaction.js";

/**
 * A text message part
 */
export type TextPartResponse = {
  /**
   * Indicates this is a text message part
   */
  type: "text";
  /**
   * The text content
   */
  value: string;
  /**
   * Reactions on this message part
   */
  reactions: Array<Reaction> | null;
};

/** @internal */
export const TextPartResponse$inboundSchema: z.ZodMiniType<
  TextPartResponse,
  unknown
> = z.object({
  type: types.literal("text"),
  value: types.string(),
  reactions: types.nullable(z.array(Reaction$inboundSchema)),
});

export function textPartResponseFromJSON(
  jsonString: string,
): SafeParseResult<TextPartResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => TextPartResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'TextPartResponse' from JSON`,
  );
}
