/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";

export type UpdateChatRequest = {
  /**
   * New display name for the chat (group chats only)
   */
  displayName?: string | undefined;
  /**
   * URL of an image to set as the group chat icon (group chats only)
   */
  groupChatIcon?: string | undefined;
};

/** @internal */
export type UpdateChatRequest$Outbound = {
  display_name?: string | undefined;
  group_chat_icon?: string | undefined;
};

/** @internal */
export const UpdateChatRequest$outboundSchema: z.ZodMiniType<
  UpdateChatRequest$Outbound,
  UpdateChatRequest
> = z.pipe(
  z.object({
    displayName: z.optional(z.string()),
    groupChatIcon: z.optional(z.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      displayName: "display_name",
      groupChatIcon: "group_chat_icon",
    });
  }),
);

export function updateChatRequestToJSON(
  updateChatRequest: UpdateChatRequest,
): string {
  return JSON.stringify(
    UpdateChatRequest$outboundSchema.parse(updateChatRequest),
  );
}
