/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import {
  WebhookEventType,
  WebhookEventType$outboundSchema,
} from "./webhook-event-type.js";

export type UpdateWebhookSubscriptionRequest = {
  /**
   * New target URL for webhook events
   */
  targetUrl?: string | undefined;
  /**
   * Updated list of event types to subscribe to
   */
  subscribedEvents?: Array<WebhookEventType> | undefined;
  /**
   * Activate or deactivate the subscription
   */
  isActive?: boolean | undefined;
};

/** @internal */
export type UpdateWebhookSubscriptionRequest$Outbound = {
  target_url?: string | undefined;
  subscribed_events?: Array<string> | undefined;
  is_active?: boolean | undefined;
};

/** @internal */
export const UpdateWebhookSubscriptionRequest$outboundSchema: z.ZodMiniType<
  UpdateWebhookSubscriptionRequest$Outbound,
  UpdateWebhookSubscriptionRequest
> = z.pipe(
  z.object({
    targetUrl: z.optional(z.string()),
    subscribedEvents: z.optional(z.array(WebhookEventType$outboundSchema)),
    isActive: z.optional(z.boolean()),
  }),
  z.transform((v) => {
    return remap$(v, {
      targetUrl: "target_url",
      subscribedEvents: "subscribed_events",
      isActive: "is_active",
    });
  }),
);

export function updateWebhookSubscriptionRequestToJSON(
  updateWebhookSubscriptionRequest: UpdateWebhookSubscriptionRequest,
): string {
  return JSON.stringify(
    UpdateWebhookSubscriptionRequest$outboundSchema.parse(
      updateWebhookSubscriptionRequest,
    ),
  );
}
