/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type VoiceMemoAttachment = {
  /**
   * Attachment identifier
   */
  id: string;
  /**
   * CDN URL for downloading the voice memo
   */
  url: string;
  /**
   * Original filename
   */
  filename: string;
  /**
   * Audio MIME type
   */
  mimeType: string;
  /**
   * File size in bytes
   */
  sizeBytes: number;
  /**
   * Duration in milliseconds
   */
  durationMs?: number | null | undefined;
};

/** @internal */
export const VoiceMemoAttachment$inboundSchema: z.ZodMiniType<
  VoiceMemoAttachment,
  unknown
> = z.pipe(
  z.object({
    id: types.string(),
    url: types.string(),
    filename: types.string(),
    mime_type: types.string(),
    size_bytes: types.number(),
    duration_ms: z.optional(z.nullable(types.number())),
  }),
  z.transform((v) => {
    return remap$(v, {
      "mime_type": "mimeType",
      "size_bytes": "sizeBytes",
      "duration_ms": "durationMs",
    });
  }),
);

export function voiceMemoAttachmentFromJSON(
  jsonString: string,
): SafeParseResult<VoiceMemoAttachment, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => VoiceMemoAttachment$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'VoiceMemoAttachment' from JSON`,
  );
}
