/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";
import {
  WebhookEventType,
  WebhookEventType$inboundSchema,
} from "./webhook-event-type.js";

export type WebhookSubscriptionResponse = {
  /**
   * Unique identifier for the webhook subscription
   */
  id: string;
  /**
   * URL where webhook events will be sent
   */
  targetUrl: string;
  /**
   * List of event types this subscription receives
   */
  subscribedEvents: Array<WebhookEventType>;
  /**
   * Whether this subscription is currently active
   */
  isActive: boolean;
  /**
   * When the subscription was created
   */
  createdAt: Date;
  /**
   * When the subscription was last updated
   */
  updatedAt: Date;
};

/** @internal */
export const WebhookSubscriptionResponse$inboundSchema: z.ZodMiniType<
  WebhookSubscriptionResponse,
  unknown
> = z.pipe(
  z.object({
    id: types.string(),
    target_url: types.string(),
    subscribed_events: z.array(WebhookEventType$inboundSchema),
    is_active: types.boolean(),
    created_at: types.date(),
    updated_at: types.date(),
  }),
  z.transform((v) => {
    return remap$(v, {
      "target_url": "targetUrl",
      "subscribed_events": "subscribedEvents",
      "is_active": "isActive",
      "created_at": "createdAt",
      "updated_at": "updatedAt",
    });
  }),
);

export function webhookSubscriptionResponseFromJSON(
  jsonString: string,
): SafeParseResult<WebhookSubscriptionResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => WebhookSubscriptionResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'WebhookSubscriptionResponse' from JSON`,
  );
}
