/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Error codes that appear in webhook failure events (`message.failed`,
 *
 * @remarks
 * `chat.group_name_update_failed`, `chat.group_icon_update_failed`).
 *
 * | Code | Name | Description | Recommended Action |
 * |------|------|-------------|-------------------|
 * | 3007 | `retries_exhausted` | Maximum delivery attempts exceeded | Retry after delay |
 * | 4001 | `delivery_failed` | Request could not be delivered | Check phone status |
 */
export const WebhookErrorCode = {
  ThreeThousandAndSeven: 3007,
  FourThousandAndOne: 4001,
} as const;
/**
 * Error codes that appear in webhook failure events (`message.failed`,
 *
 * @remarks
 * `chat.group_name_update_failed`, `chat.group_icon_update_failed`).
 *
 * | Code | Name | Description | Recommended Action |
 * |------|------|-------------|-------------------|
 * | 3007 | `retries_exhausted` | Maximum delivery attempts exceeded | Retry after delay |
 * | 4001 | `delivery_failed` | Request could not be delivered | Check phone status |
 */
export type WebhookErrorCode = ClosedEnum<typeof WebhookErrorCode>;

/** @internal */
export const WebhookErrorCode$inboundSchema: z.ZodMiniEnum<
  typeof WebhookErrorCode
> = z.enum(WebhookErrorCode);
/** @internal */
export const WebhookErrorCode$outboundSchema: z.ZodMiniEnum<
  typeof WebhookErrorCode
> = WebhookErrorCode$inboundSchema;
