/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as openEnums from "../../types/enums.js";
import { OpenEnum } from "../../types/enums.js";

/**
 * Valid webhook event types that can be subscribed to
 */
export const WebhookEventType = {
  MessageSent: "message.sent",
  MessageReceived: "message.received",
  MessageRead: "message.read",
  MessageDelivered: "message.delivered",
  MessageFailed: "message.failed",
  ReactionAdded: "reaction.added",
  ReactionRemoved: "reaction.removed",
  ParticipantAdded: "participant.added",
  ParticipantRemoved: "participant.removed",
  ChatCreated: "chat.created",
  ChatGroupNameUpdated: "chat.group_name_updated",
  ChatGroupIconUpdated: "chat.group_icon_updated",
  ChatGroupNameUpdateFailed: "chat.group_name_update_failed",
  ChatGroupIconUpdateFailed: "chat.group_icon_update_failed",
  ChatTypingIndicatorStarted: "chat.typing_indicator.started",
  ChatTypingIndicatorStopped: "chat.typing_indicator.stopped",
} as const;
/**
 * Valid webhook event types that can be subscribed to
 */
export type WebhookEventType = OpenEnum<typeof WebhookEventType>;

/** @internal */
export const WebhookEventType$inboundSchema: z.ZodMiniType<
  WebhookEventType,
  unknown
> = openEnums.inboundSchema(WebhookEventType);
/** @internal */
export const WebhookEventType$outboundSchema: z.ZodMiniType<
  string,
  WebhookEventType
> = openEnums.outboundSchema(WebhookEventType);
