/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { LinqCore } from "../core.js";
import * as components from "../models/components/index.js";
import { SDKValidationError } from "../models/errors/sdk-validation-error.js";
import { ERR, Result } from "../types/fp.js";

export async function validateWebhook(_client: LinqCore, {
  request: rawRequest,
}: {
  request: {
    body: BodyInit;
    method: string;
    url: string;
    headers: Record<string, string> | Headers;
  } | Request;
}): Promise<
  Result<
    | components.MessageSentWebhookV2
    | components.MessageReceivedWebhookV2
    | components.MessageReadWebhookV2
    | components.MessageDeliveredWebhookV2
    | components.MessageFailedWebhook
    | components.ReactionAddedWebhook
    | components.ReactionRemovedWebhook
    | components.ParticipantAddedWebhook
    | components.ParticipantRemovedWebhook
    | components.ChatGroupNameUpdatedWebhook
    | components.ChatGroupIconUpdatedWebhook
    | components.ChatGroupNameUpdateFailedWebhook
    | components.ChatGroupIconUpdateFailedWebhook
    | components.ChatCreatedWebhook
    | components.ChatTypingIndicatorStartedWebhook
    | components.ChatTypingIndicatorStoppedWebhook,
    SDKValidationError
  >
> {
  const request = normalizeRequest(rawRequest);
  const knownSchemas = [
    components.messageSentWebhookV2FromJSON,
    components.messageReceivedWebhookV2FromJSON,
    components.messageReadWebhookV2FromJSON,
    components.messageDeliveredWebhookV2FromJSON,
    components.messageFailedWebhookFromJSON,
    components.reactionAddedWebhookFromJSON,
    components.reactionRemovedWebhookFromJSON,
    components.participantAddedWebhookFromJSON,
    components.participantRemovedWebhookFromJSON,
    components.chatGroupNameUpdatedWebhookFromJSON,
    components.chatGroupIconUpdatedWebhookFromJSON,
    components.chatGroupNameUpdateFailedWebhookFromJSON,
    components.chatGroupIconUpdateFailedWebhookFromJSON,
    components.chatCreatedWebhookFromJSON,
    components.chatTypingIndicatorStartedWebhookFromJSON,
    components.chatTypingIndicatorStoppedWebhookFromJSON,
  ];

  const jsonString = await request.text();

  for (const schema of knownSchemas) {
    const ret = schema(jsonString);
    if (ret.ok) {
      return ret;
    }
  }

  return ERR(
    new SDKValidationError(
      "No matching schema found for the given webhook payload",
      jsonString,
      jsonString,
    ),
  );
}

function normalizeRequest(
  request: {
    body: BodyInit;
    method: string;
    url: string;
    headers: Record<string, string> | Headers;
  } | Request,
): Request {
  if (request instanceof Request) {
    return request;
  }
  return new Request(request.url, request);
}
