/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { attachmentsGetAttachment } from "../funcs/attachments-get-attachment.js";
import { attachmentsRequestUpload } from "../funcs/attachments-request-upload.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Attachments extends ClientSDK {
  /**
   * Pre-upload a file
   *
   * @remarks
   * **This endpoint is optional.** You can send media by simply providing a URL in your
   * message's media part — no pre-upload required. Use this endpoint only when you want
   * to upload a file ahead of time for reuse or latency optimization.
   *
   * Returns a presigned upload URL and a permanent `attachment_id` you can reference
   * in future messages.
   *
   * ## Step 1: Request an upload URL
   *
   * Call this endpoint with file metadata:
   *
   * ```json
   * POST /v3/attachments
   * {
   *   "filename": "photo.jpg",
   *   "content_type": "image/jpeg",
   *   "size_bytes": 1024000
   * }
   * ```
   *
   * The response includes an `upload_url` (valid for 15 minutes) and a permanent `attachment_id`.
   *
   * ## Step 2: Upload the file
   *
   * Make a PUT request to the `upload_url` with the raw file bytes as the request body.. Include the headers from `required_headers`.
   * The request body is the binary file content — **not** JSON, **not** multipart form data.
   *
   * ```bash
   * curl -X PUT "<upload_url from step 1>" \
   *   -H "Content-Type: image/jpeg" \
   *   --data-binary @filebytes
   * ```
   *
   * ## Step 3: Send a message with the attachment
   *
   * Reference the `attachment_id` in a media part. The ID never expires — use it in as many messages as you want.
   *
   * ```json
   * POST /v3/messages
   * {
   *   "to": ["+15551234567"],
   *   "from": "+15559876543",
   *   "parts": [
   *     { "type": "media", "attachment_id": "<attachment_id from step 1>" }
   *   ]
   * }
   * ```
   *
   * ## When to use this instead of a URL in the media part
   *
   * - Sending the same file to multiple recipients (avoids re-downloading each time)
   * - Large files where you want to separate upload from message send
   * - Latency-sensitive sends where the file should already be stored
   *
   * If you just need to send a file once, skip all of this and pass a `url` directly in the media part instead.
   *
   * **File Size Limit:** 100MB
   *
   * **Unsupported Types:** WebP, SVG, FLAC, OGG, and executable files are explicitly rejected.
   */
  async requestUpload(
    request: components.RequestUploadRequest,
    options?: RequestOptions,
  ): Promise<components.RequestUploadResult> {
    return unwrapAsync(attachmentsRequestUpload(
      this,
      request,
      options,
    ));
  }

  /**
   * Get attachment metadata
   *
   * @remarks
   * Retrieve metadata for a specific attachment including its status,
   * file information, and URLs for downloading.
   */
  async getAttachment(
    attachmentId: string,
    options?: RequestOptions,
  ): Promise<components.Attachment> {
    return unwrapAsync(attachmentsGetAttachment(
      this,
      attachmentId,
      options,
    ));
  }
}
