/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { chatsAddParticipant } from "../funcs/chats-add-participant.js";
import { chatsCreateChat } from "../funcs/chats-create-chat.js";
import { chatsGetChat } from "../funcs/chats-get-chat.js";
import { chatsListChats } from "../funcs/chats-list-chats.js";
import { chatsMarkChatAsRead } from "../funcs/chats-mark-chat-as-read.js";
import { chatsRemoveParticipant } from "../funcs/chats-remove-participant.js";
import { chatsShareContactWithChat } from "../funcs/chats-share-contact-with-chat.js";
import { chatsStartTyping } from "../funcs/chats-start-typing.js";
import { chatsStopTyping } from "../funcs/chats-stop-typing.js";
import { chatsUpdateChat } from "../funcs/chats-update-chat.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Chats extends ClientSDK {
  /**
   * Create a new chat
   *
   * @remarks
   * Create a new chat with specified participants and send an initial message.
   * The initial message is required when creating a chat.
   *
   * ## Message Effects
   *
   * You can add iMessage effects to make your messages more expressive. Effects are
   * optional and can be either screen effects (full-screen animations) or bubble effects
   * (message bubble animations).
   *
   * **Screen Effects:** `confetti`, `fireworks`, `lasers`, `sparkles`, `celebration`,
   * `hearts`, `love`, `balloons`, `happy_birthday`, `echo`, `spotlight`
   *
   * **Bubble Effects:** `slam`, `loud`, `gentle`, `invisible`
   *
   * Only one effect type can be applied per message.
   */
  async createChat(
    request: components.CreateChatRequest,
    options?: RequestOptions,
  ): Promise<components.CreateChatResult> {
    return unwrapAsync(chatsCreateChat(
      this,
      request,
      options,
    ));
  }

  /**
   * List all chats
   *
   * @remarks
   * Retrieves a paginated list of chats for the authenticated partner filtered by phone number.
   * Returns all chats involving the specified phone number with their participants and recent activity.
   *
   * **Pagination:**
   * - Use `limit` to control page size (default: 20, max: 100)
   * - The response includes `next_cursor` for fetching the next page
   * - When `next_cursor` is `null`, there are no more results to fetch
   * - Pass the `next_cursor` value as the `cursor` parameter for the next request
   *
   * **Example pagination flow:**
   * 1. First request: `GET /v3/chats?from=%2B12223334444&limit=20`
   * 2. Response includes `next_cursor: "20"` (more results exist)
   * 3. Next request: `GET /v3/chats?from=%2B12223334444&limit=20&cursor=20`
   * 4. Response includes `next_cursor: null` (no more results)
   */
  async listChats(
    from: string,
    limit?: number | undefined,
    cursor?: string | undefined,
    options?: RequestOptions,
  ): Promise<components.ListChatsResult> {
    return unwrapAsync(chatsListChats(
      this,
      from,
      limit,
      cursor,
      options,
    ));
  }

  /**
   * Get a chat by ID
   *
   * @remarks
   * Retrieve a chat by its unique identifier.
   */
  async getChat(
    chatId: string,
    options?: RequestOptions,
  ): Promise<components.Chat> {
    return unwrapAsync(chatsGetChat(
      this,
      chatId,
      options,
    ));
  }

  /**
   * Update a chat
   *
   * @remarks
   * Update chat properties such as display name and group chat icon.
   */
  async updateChat(
    chatId: string,
    body: components.UpdateChatRequest,
    options?: RequestOptions,
  ): Promise<components.Chat> {
    return unwrapAsync(chatsUpdateChat(
      this,
      chatId,
      body,
      options,
    ));
  }

  /**
   * Add a participant to a chat
   *
   * @remarks
   * Add a new participant to an existing group chat.
   *
   * **Requirements:**
   * - Group chats only (3+ existing participants)
   * - New participant must support the same messaging service as the group
   * - Cross-service additions not allowed (e.g., can't add RCS-only user to iMessage group)
   * - For cross-service scenarios, create a new chat instead
   */
  async addParticipant(
    chatId: string,
    body: components.AddParticipantRequest,
    options?: RequestOptions,
  ): Promise<operations.AddParticipantResponse> {
    return unwrapAsync(chatsAddParticipant(
      this,
      chatId,
      body,
      options,
    ));
  }

  /**
   * Remove a participant from a chat
   *
   * @remarks
   * Remove a participant from an existing group chat.
   *
   * **Requirements:**
   * - Group chats only
   * - Must have 3+ participants after removal
   */
  async removeParticipant(
    chatId: string,
    body: components.RemoveParticipantRequest,
    options?: RequestOptions,
  ): Promise<operations.RemoveParticipantResponse> {
    return unwrapAsync(chatsRemoveParticipant(
      this,
      chatId,
      body,
      options,
    ));
  }

  /**
   * Start typing indicator
   *
   * @remarks
   * Send a typing indicator to show that someone is typing in the chat.
   *
   * **Note:** Group chat typing indicators are not currently supported.
   */
  async startTyping(
    chatId: string,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(chatsStartTyping(
      this,
      chatId,
      options,
    ));
  }

  /**
   * Stop typing indicator
   *
   * @remarks
   * Stop the typing indicator for the chat.
   *
   * **Note:** Typing indicators are automatically stopped when a message is sent,
   * so calling this endpoint after sending a message is unnecessary.
   *
   * **Note:** Group chat typing indicators are not currently supported.
   */
  async stopTyping(
    chatId: string,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(chatsStopTyping(
      this,
      chatId,
      options,
    ));
  }

  /**
   * Mark chat as read
   *
   * @remarks
   * Mark all messages in a chat as read.
   */
  async markChatAsRead(
    chatId: string,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(chatsMarkChatAsRead(
      this,
      chatId,
      options,
    ));
  }

  /**
   * Share your contact card with a chat
   *
   * @remarks
   * Share your contact information (Name and Photo Sharing) with a chat.
   */
  async shareContactWithChat(
    chatId: string,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(chatsShareContactWithChat(
      this,
      chatId,
      options,
    ));
  }
}
