/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { messagesDeleteMessage } from "../funcs/messages-delete-message.js";
import { messagesGetMessageThread } from "../funcs/messages-get-message-thread.js";
import { messagesGetMessage } from "../funcs/messages-get-message.js";
import { messagesGetMessages } from "../funcs/messages-get-messages.js";
import { messagesSendMessageToChat } from "../funcs/messages-send-message-to-chat.js";
import { messagesSendReaction } from "../funcs/messages-send-reaction.js";
import { messagesSendVoiceMemoToChat } from "../funcs/messages-send-voice-memo-to-chat.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Messages extends ClientSDK {
  /**
   * Send a message to an existing chat
   *
   * @remarks
   * Send a message to an existing chat. Use this endpoint when you already have
   * a chat ID and want to send additional messages to it.
   *
   * ## Message Effects
   *
   * You can add iMessage effects to make your messages more expressive. Effects are
   * optional and can be either screen effects (full-screen animations) or bubble effects
   * (message bubble animations).
   *
   * **Screen Effects:** `confetti`, `fireworks`, `lasers`, `sparkles`, `celebration`,
   * `hearts`, `love`, `balloons`, `happy_birthday`, `echo`, `spotlight`
   *
   * **Bubble Effects:** `slam`, `loud`, `gentle`, `invisible`
   *
   * Only one effect type can be applied per message.
   */
  async sendMessageToChat(
    chatId: string,
    body: components.SendMessageToChatRequest,
    options?: RequestOptions,
  ): Promise<components.SendMessageResponse> {
    return unwrapAsync(messagesSendMessageToChat(
      this,
      chatId,
      body,
      options,
    ));
  }

  /**
   * Get messages from a chat
   *
   * @remarks
   * Retrieve messages from a specific chat with pagination support.
   */
  async getMessages(
    chatId: string,
    cursor?: string | undefined,
    limit?: number | undefined,
    options?: RequestOptions,
  ): Promise<components.GetMessagesResult> {
    return unwrapAsync(messagesGetMessages(
      this,
      chatId,
      cursor,
      limit,
      options,
    ));
  }

  /**
   * Get all messages in a thread
   *
   * @remarks
   * Retrieve all messages in a conversation thread. Given any message ID in the thread,
   * returns the originator message and all replies in chronological order.
   *
   * If the message is not part of a thread, returns just that single message.
   *
   * Supports pagination and configurable ordering.
   */
  async getMessageThread(
    messageId: string,
    cursor?: string | undefined,
    limit?: number | undefined,
    order?: operations.Order | undefined,
    options?: RequestOptions,
  ): Promise<components.GetThreadResponse> {
    return unwrapAsync(messagesGetMessageThread(
      this,
      messageId,
      cursor,
      limit,
      order,
      options,
    ));
  }

  /**
   * Send a voice memo to a chat
   *
   * @remarks
   * Send a voice memo to all participants in a chat. Voice memos MUST be sent alone without text
   * or other attachments.
   *
   * **Supported audio formats:**
   * - MP3 (audio/mpeg)
   * - M4A (audio/x-m4a, audio/mp4)
   * - AAC (audio/aac)
   * - CAF (audio/x-caf) - Core Audio Format
   * - WAV (audio/wav)
   * - AIFF (audio/aiff, audio/x-aiff)
   * - AMR (audio/amr)
   */
  async sendVoiceMemoToChat(
    chatId: string,
    body: components.SendVoiceMemoToChatRequest,
    options?: RequestOptions,
  ): Promise<components.SendVoiceMemoToChatResult> {
    return unwrapAsync(messagesSendVoiceMemoToChat(
      this,
      chatId,
      body,
      options,
    ));
  }

  /**
   * Get a message by ID
   *
   * @remarks
   * Retrieve a specific message by its ID. This endpoint returns the full message
   * details including text, attachments, reactions, and metadata.
   */
  async getMessage(
    messageId: string,
    options?: RequestOptions,
  ): Promise<components.Message> {
    return unwrapAsync(messagesGetMessage(
      this,
      messageId,
      options,
    ));
  }

  /**
   * Delete a message from system
   *
   * @remarks
   * Deletes a message from the Linq API only. This does NOT unsend or remove the message
   * from the actual chat - recipients will still see the message.
   *
   * Use this endpoint to remove messages from your records and prevent them from appearing
   * in API responses.
   */
  async deleteMessage(
    messageId: string,
    body: components.DeleteMessageRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(messagesDeleteMessage(
      this,
      messageId,
      body,
      options,
    ));
  }

  /**
   * Add or remove a reaction to a message
   *
   * @remarks
   * Add or remove emoji reactions to messages. Reactions let users express
   * their response to a message without sending a new message.
   *
   * **Supported Reactions:**
   * - love ❤️
   * - like 👍
   * - dislike 👎
   * - laugh 😂
   * - emphasize ‼️
   * - question ❓
   * - custom - any emoji (use `custom_emoji` field to specify)
   */
  async sendReaction(
    messageId: string,
    body: components.SendReactionRequest,
    options?: RequestOptions,
  ): Promise<components.Reaction> {
    return unwrapAsync(messagesSendReaction(
      this,
      messageId,
      body,
      options,
    ));
  }
}
