/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { phoneNumbersListPhoneNumbers } from "../funcs/phone-numbers-list-phone-numbers.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";

export class PhoneNumbers extends ClientSDK {
  /**
   * List phone numbers
   *
   * @remarks
   * Returns all phone numbers assigned to the authenticated partner.
   * Use this endpoint to discover which phone numbers are available for
   * sending messages via the `from` field in create chat and send message requests.
   */
  async listPhoneNumbers(
    options?: RequestOptions,
  ): Promise<components.ListPhoneNumbersResult> {
    return unwrapAsync(phoneNumbersListPhoneNumbers(
      this,
      options,
    ));
  }
}
