/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { validateWebhook } from "../funcs/validate-webhook.js";
import { ClientSDK } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";
import { Attachments } from "./attachments.js";
import { Chats } from "./chats.js";
import { Messages } from "./messages.js";
import { PhoneNumbers } from "./phone-numbers.js";
import { Webhooks } from "./webhooks.js";

export class Linq extends ClientSDK {
  private _chats?: Chats;
  get chats(): Chats {
    return (this._chats ??= new Chats(this._options));
  }

  private _messages?: Messages;
  get messages(): Messages {
    return (this._messages ??= new Messages(this._options));
  }

  private _attachments?: Attachments;
  get attachments(): Attachments {
    return (this._attachments ??= new Attachments(this._options));
  }

  private _phoneNumbers?: PhoneNumbers;
  get phoneNumbers(): PhoneNumbers {
    return (this._phoneNumbers ??= new PhoneNumbers(this._options));
  }

  private _webhooks?: Webhooks;
  get webhooks(): Webhooks {
    return (this._webhooks ??= new Webhooks(this._options));
  }

  async validateWebhook({
    request,
  }: {
    request: {
      body: string;
      headers: Record<string, string> | Headers;
      url: string;
      method: string;
    } | Request;
  }): Promise<
    | components.MessageSentWebhookV2
    | components.MessageReceivedWebhookV2
    | components.MessageReadWebhookV2
    | components.MessageDeliveredWebhookV2
    | components.MessageFailedWebhook
    | components.ReactionAddedWebhook
    | components.ReactionRemovedWebhook
    | components.ParticipantAddedWebhook
    | components.ParticipantRemovedWebhook
    | components.ChatGroupNameUpdatedWebhook
    | components.ChatGroupIconUpdatedWebhook
    | components.ChatGroupNameUpdateFailedWebhook
    | components.ChatGroupIconUpdateFailedWebhook
    | components.ChatCreatedWebhook
    | components.ChatTypingIndicatorStartedWebhook
    | components.ChatTypingIndicatorStoppedWebhook
  > {
    return unwrapAsync(validateWebhook(
      this,
      { request },
    ));
  }
}
