/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { webhooksCreateWebhookSubscription } from "../funcs/webhooks-create-webhook-subscription.js";
import { webhooksDeleteWebhookSubscription } from "../funcs/webhooks-delete-webhook-subscription.js";
import { webhooksGetWebhookSubscription } from "../funcs/webhooks-get-webhook-subscription.js";
import { webhooksListWebhookEvents } from "../funcs/webhooks-list-webhook-events.js";
import { webhooksListWebhookSubscriptions } from "../funcs/webhooks-list-webhook-subscriptions.js";
import { webhooksUpdateWebhookSubscription } from "../funcs/webhooks-update-webhook-subscription.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Webhooks extends ClientSDK {
  /**
   * List available webhook event types
   *
   * @remarks
   * Returns all available webhook event types that can be subscribed to.
   * Use this endpoint to discover valid values for the `subscribed_events`
   * field when creating or updating webhook subscriptions.
   */
  async listWebhookEvents(
    options?: RequestOptions,
  ): Promise<components.WebhookEventsResult> {
    return unwrapAsync(webhooksListWebhookEvents(
      this,
      options,
    ));
  }

  /**
   * Create a new webhook subscription
   *
   * @remarks
   * Create a new webhook subscription to receive events at a target URL.
   * Upon creation, a signing secret is generated for verifying webhook
   * authenticity. **Store this secret securely — it cannot be retrieved later.**
   *
   * **Webhook Delivery:**
   * - Events are sent via HTTP POST to the target URL
   * - Each request includes `X-Webhook-Signature` and `X-Webhook-Timestamp` headers
   * - Signature is HMAC-SHA256 over `{timestamp}.{payload}` — see [Webhook Events](/docs/webhook-events) for verification details
   * - Failed deliveries (5xx, 429, network errors) are retried up to 6 times with exponential backoff: 2s, 4s, 8s, 16s, 30s
   * - Client errors (4xx except 429) are not retried
   */
  async createWebhookSubscription(
    request: components.CreateWebhookSubscriptionRequest,
    options?: RequestOptions,
  ): Promise<components.WebhookSubscriptionCreatedResponse> {
    return unwrapAsync(webhooksCreateWebhookSubscription(
      this,
      request,
      options,
    ));
  }

  /**
   * List all webhook subscriptions
   *
   * @remarks
   * Retrieve all webhook subscriptions for the authenticated partner.
   * Returns a list of active and inactive subscriptions with their
   * configuration and status.
   */
  async listWebhookSubscriptions(
    options?: RequestOptions,
  ): Promise<components.ListWebhookSubscriptionsResult> {
    return unwrapAsync(webhooksListWebhookSubscriptions(
      this,
      options,
    ));
  }

  /**
   * Get a webhook subscription by ID
   *
   * @remarks
   * Retrieve details for a specific webhook subscription including its
   * target URL, subscribed events, and current status.
   */
  async getWebhookSubscription(
    subscriptionId: string,
    options?: RequestOptions,
  ): Promise<components.WebhookSubscriptionResponse> {
    return unwrapAsync(webhooksGetWebhookSubscription(
      this,
      subscriptionId,
      options,
    ));
  }

  /**
   * Update a webhook subscription
   *
   * @remarks
   * Update an existing webhook subscription. You can modify the target URL,
   * subscribed events, or activate/deactivate the subscription.
   *
   * **Note:** The signing secret cannot be changed via this endpoint.
   */
  async updateWebhookSubscription(
    subscriptionId: string,
    body: components.UpdateWebhookSubscriptionRequest,
    options?: RequestOptions,
  ): Promise<components.WebhookSubscriptionResponse> {
    return unwrapAsync(webhooksUpdateWebhookSubscription(
      this,
      subscriptionId,
      body,
      options,
    ));
  }

  /**
   * Delete a webhook subscription
   *
   * @remarks
   * Delete a webhook subscription.
   */
  async deleteWebhookSubscription(
    subscriptionId: string,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(webhooksDeleteWebhookSubscription(
      this,
      subscriptionId,
      options,
    ));
  }
}
