/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type AddParticipantRequest = {
  /**
   * Unique identifier of the chat
   */
  chatId: string;
  body: components.AddParticipantRequest;
};

/**
 * Participant addition queued successfully
 */
export type AddParticipantResponse = {
  status?: string | undefined;
  traceId?: string | undefined;
  message?: string | undefined;
};

/** @internal */
export type AddParticipantRequest$Outbound = {
  chatId: string;
  body: components.AddParticipantRequest$Outbound;
};

/** @internal */
export const AddParticipantRequest$outboundSchema: z.ZodMiniType<
  AddParticipantRequest$Outbound,
  AddParticipantRequest
> = z.object({
  chatId: z.string(),
  body: components.AddParticipantRequest$outboundSchema,
});

export function addParticipantRequestToJSON(
  addParticipantRequest: AddParticipantRequest,
): string {
  return JSON.stringify(
    AddParticipantRequest$outboundSchema.parse(addParticipantRequest),
  );
}

/** @internal */
export const AddParticipantResponse$inboundSchema: z.ZodMiniType<
  AddParticipantResponse,
  unknown
> = z.pipe(
  z.object({
    status: types.optional(types.string()),
    trace_id: types.optional(types.string()),
    message: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "trace_id": "traceId",
    });
  }),
);

export function addParticipantResponseFromJSON(
  jsonString: string,
): SafeParseResult<AddParticipantResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AddParticipantResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AddParticipantResponse' from JSON`,
  );
}
