/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as components from "../components/index.js";

export type DeleteMessageRequest = {
  /**
   * Unique identifier of the message to delete
   */
  messageId: string;
  body: components.DeleteMessageRequest;
};

/** @internal */
export type DeleteMessageRequest$Outbound = {
  messageId: string;
  body: components.DeleteMessageRequest$Outbound;
};

/** @internal */
export const DeleteMessageRequest$outboundSchema: z.ZodMiniType<
  DeleteMessageRequest$Outbound,
  DeleteMessageRequest
> = z.object({
  messageId: z.string(),
  body: components.DeleteMessageRequest$outboundSchema,
});

export function deleteMessageRequestToJSON(
  deleteMessageRequest: DeleteMessageRequest,
): string {
  return JSON.stringify(
    DeleteMessageRequest$outboundSchema.parse(deleteMessageRequest),
  );
}
