/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type DeleteWebhookSubscriptionRequest = {
  /**
   * Unique identifier of the webhook subscription
   */
  subscriptionId: string;
};

/** @internal */
export type DeleteWebhookSubscriptionRequest$Outbound = {
  subscriptionId: string;
};

/** @internal */
export const DeleteWebhookSubscriptionRequest$outboundSchema: z.ZodMiniType<
  DeleteWebhookSubscriptionRequest$Outbound,
  DeleteWebhookSubscriptionRequest
> = z.object({
  subscriptionId: z.string(),
});

export function deleteWebhookSubscriptionRequestToJSON(
  deleteWebhookSubscriptionRequest: DeleteWebhookSubscriptionRequest,
): string {
  return JSON.stringify(
    DeleteWebhookSubscriptionRequest$outboundSchema.parse(
      deleteWebhookSubscriptionRequest,
    ),
  );
}
