/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetMessagesRequest = {
  /**
   * Unique identifier of the chat
   */
  chatId: string;
  /**
   * Pagination cursor from previous next_cursor response
   */
  cursor?: string | undefined;
  /**
   * Maximum number of messages to return
   */
  limit?: number | undefined;
};

/** @internal */
export type GetMessagesRequest$Outbound = {
  chatId: string;
  cursor?: string | undefined;
  limit: number;
};

/** @internal */
export const GetMessagesRequest$outboundSchema: z.ZodMiniType<
  GetMessagesRequest$Outbound,
  GetMessagesRequest
> = z.object({
  chatId: z.string(),
  cursor: z.optional(z.string()),
  limit: z._default(z.int(), 50),
});

export function getMessagesRequestToJSON(
  getMessagesRequest: GetMessagesRequest,
): string {
  return JSON.stringify(
    GetMessagesRequest$outboundSchema.parse(getMessagesRequest),
  );
}
