/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetChatRequest = {
  /**
   * Unique identifier of the chat
   */
  chatId: string;
};

/** @internal */
export type GetChatRequest$Outbound = {
  chatId: string;
};

/** @internal */
export const GetChatRequest$outboundSchema: z.ZodMiniType<
  GetChatRequest$Outbound,
  GetChatRequest
> = z.object({
  chatId: z.string(),
});

export function getChatRequestToJSON(getChatRequest: GetChatRequest): string {
  return JSON.stringify(GetChatRequest$outboundSchema.parse(getChatRequest));
}
