/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type GetWebhookSubscriptionRequest = {
  /**
   * Unique identifier of the webhook subscription
   */
  subscriptionId: string;
};

/** @internal */
export type GetWebhookSubscriptionRequest$Outbound = {
  subscriptionId: string;
};

/** @internal */
export const GetWebhookSubscriptionRequest$outboundSchema: z.ZodMiniType<
  GetWebhookSubscriptionRequest$Outbound,
  GetWebhookSubscriptionRequest
> = z.object({
  subscriptionId: z.string(),
});

export function getWebhookSubscriptionRequestToJSON(
  getWebhookSubscriptionRequest: GetWebhookSubscriptionRequest,
): string {
  return JSON.stringify(
    GetWebhookSubscriptionRequest$outboundSchema.parse(
      getWebhookSubscriptionRequest,
    ),
  );
}
