/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { ClosedEnum } from "../../types/enums.js";

/**
 * Sort order for messages (asc = oldest first, desc = newest first)
 */
export const Order = {
  Asc: "asc",
  Desc: "desc",
} as const;
/**
 * Sort order for messages (asc = oldest first, desc = newest first)
 */
export type Order = ClosedEnum<typeof Order>;

export type GetMessageThreadRequest = {
  /**
   * ID of any message in the thread (can be originator or any reply)
   */
  messageId: string;
  /**
   * Pagination cursor from previous next_cursor response
   */
  cursor?: string | undefined;
  /**
   * Maximum number of messages to return
   */
  limit?: number | undefined;
  /**
   * Sort order for messages (asc = oldest first, desc = newest first)
   */
  order?: Order | undefined;
};

/** @internal */
export const Order$outboundSchema: z.ZodMiniEnum<typeof Order> = z.enum(Order);

/** @internal */
export type GetMessageThreadRequest$Outbound = {
  messageId: string;
  cursor?: string | undefined;
  limit: number;
  order: string;
};

/** @internal */
export const GetMessageThreadRequest$outboundSchema: z.ZodMiniType<
  GetMessageThreadRequest$Outbound,
  GetMessageThreadRequest
> = z.object({
  messageId: z.string(),
  cursor: z.optional(z.string()),
  limit: z._default(z.int(), 50),
  order: z._default(Order$outboundSchema, "asc"),
});

export function getMessageThreadRequestToJSON(
  getMessageThreadRequest: GetMessageThreadRequest,
): string {
  return JSON.stringify(
    GetMessageThreadRequest$outboundSchema.parse(getMessageThreadRequest),
  );
}
