/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type ListChatsRequest = {
  /**
   * Phone number to filter chats by. Returns all chats made from this phone number.
   *
   * @remarks
   * Must be in E.164 format with the `+` sign URL-encoded as `%2B` (e.g., `%2B13343284472`).
   */
  from: string;
  /**
   * Maximum number of chats to return per page
   */
  limit?: number | undefined;
  /**
   * Pagination cursor from the previous response's `next_cursor` field.
   *
   * @remarks
   * Omit this parameter for the first page of results.
   */
  cursor?: string | undefined;
};

/** @internal */
export type ListChatsRequest$Outbound = {
  from: string;
  limit: number;
  cursor?: string | undefined;
};

/** @internal */
export const ListChatsRequest$outboundSchema: z.ZodMiniType<
  ListChatsRequest$Outbound,
  ListChatsRequest
> = z.object({
  from: z.string(),
  limit: z._default(z.int(), 20),
  cursor: z.optional(z.string()),
});

export function listChatsRequestToJSON(
  listChatsRequest: ListChatsRequest,
): string {
  return JSON.stringify(
    ListChatsRequest$outboundSchema.parse(listChatsRequest),
  );
}
