/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type MarkChatAsReadRequest = {
  /**
   * Unique identifier of the chat
   */
  chatId: string;
};

/** @internal */
export type MarkChatAsReadRequest$Outbound = {
  chatId: string;
};

/** @internal */
export const MarkChatAsReadRequest$outboundSchema: z.ZodMiniType<
  MarkChatAsReadRequest$Outbound,
  MarkChatAsReadRequest
> = z.object({
  chatId: z.string(),
});

export function markChatAsReadRequestToJSON(
  markChatAsReadRequest: MarkChatAsReadRequest,
): string {
  return JSON.stringify(
    MarkChatAsReadRequest$outboundSchema.parse(markChatAsReadRequest),
  );
}
