/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as types from "../../types/primitives.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdk-validation-error.js";

export type RemoveParticipantRequest = {
  /**
   * Unique identifier of the chat
   */
  chatId: string;
  body: components.RemoveParticipantRequest;
};

/**
 * Participant removal queued successfully
 */
export type RemoveParticipantResponse = {
  status?: string | undefined;
  traceId?: string | undefined;
  message?: string | undefined;
};

/** @internal */
export type RemoveParticipantRequest$Outbound = {
  chatId: string;
  body: components.RemoveParticipantRequest$Outbound;
};

/** @internal */
export const RemoveParticipantRequest$outboundSchema: z.ZodMiniType<
  RemoveParticipantRequest$Outbound,
  RemoveParticipantRequest
> = z.object({
  chatId: z.string(),
  body: components.RemoveParticipantRequest$outboundSchema,
});

export function removeParticipantRequestToJSON(
  removeParticipantRequest: RemoveParticipantRequest,
): string {
  return JSON.stringify(
    RemoveParticipantRequest$outboundSchema.parse(removeParticipantRequest),
  );
}

/** @internal */
export const RemoveParticipantResponse$inboundSchema: z.ZodMiniType<
  RemoveParticipantResponse,
  unknown
> = z.pipe(
  z.object({
    status: types.optional(types.string()),
    trace_id: types.optional(types.string()),
    message: types.optional(types.string()),
  }),
  z.transform((v) => {
    return remap$(v, {
      "trace_id": "traceId",
    });
  }),
);

export function removeParticipantResponseFromJSON(
  jsonString: string,
): SafeParseResult<RemoveParticipantResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => RemoveParticipantResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'RemoveParticipantResponse' from JSON`,
  );
}
