/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as components from "../components/index.js";

export type SendMessageToChatRequest = {
  /**
   * Unique identifier of the chat
   */
  chatId: string;
  body: components.SendMessageToChatRequest;
};

/** @internal */
export type SendMessageToChatRequest$Outbound = {
  chatId: string;
  body: components.SendMessageToChatRequest$Outbound;
};

/** @internal */
export const SendMessageToChatRequest$outboundSchema: z.ZodMiniType<
  SendMessageToChatRequest$Outbound,
  SendMessageToChatRequest
> = z.object({
  chatId: z.string(),
  body: components.SendMessageToChatRequest$outboundSchema,
});

export function sendMessageToChatRequestToJSON(
  sendMessageToChatRequest: SendMessageToChatRequest,
): string {
  return JSON.stringify(
    SendMessageToChatRequest$outboundSchema.parse(sendMessageToChatRequest),
  );
}
