/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as components from "../components/index.js";

export type SendVoiceMemoToChatRequest = {
  /**
   * Unique identifier of the chat
   */
  chatId: string;
  body: components.SendVoiceMemoToChatRequest;
};

/** @internal */
export type SendVoiceMemoToChatRequest$Outbound = {
  chatId: string;
  body: components.SendVoiceMemoToChatRequest$Outbound;
};

/** @internal */
export const SendVoiceMemoToChatRequest$outboundSchema: z.ZodMiniType<
  SendVoiceMemoToChatRequest$Outbound,
  SendVoiceMemoToChatRequest
> = z.object({
  chatId: z.string(),
  body: components.SendVoiceMemoToChatRequest$outboundSchema,
});

export function sendVoiceMemoToChatRequestToJSON(
  sendVoiceMemoToChatRequest: SendVoiceMemoToChatRequest,
): string {
  return JSON.stringify(
    SendVoiceMemoToChatRequest$outboundSchema.parse(sendVoiceMemoToChatRequest),
  );
}
