/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as components from "../components/index.js";

export type SendReactionRequest = {
  /**
   * Unique identifier of the message to react to
   */
  messageId: string;
  body: components.SendReactionRequest;
};

/** @internal */
export type SendReactionRequest$Outbound = {
  messageId: string;
  body: components.SendReactionRequest$Outbound;
};

/** @internal */
export const SendReactionRequest$outboundSchema: z.ZodMiniType<
  SendReactionRequest$Outbound,
  SendReactionRequest
> = z.object({
  messageId: z.string(),
  body: components.SendReactionRequest$outboundSchema,
});

export function sendReactionRequestToJSON(
  sendReactionRequest: SendReactionRequest,
): string {
  return JSON.stringify(
    SendReactionRequest$outboundSchema.parse(sendReactionRequest),
  );
}
