/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type ShareContactWithChatRequest = {
  /**
   * Unique identifier of the chat
   */
  chatId: string;
};

/** @internal */
export type ShareContactWithChatRequest$Outbound = {
  chatId: string;
};

/** @internal */
export const ShareContactWithChatRequest$outboundSchema: z.ZodMiniType<
  ShareContactWithChatRequest$Outbound,
  ShareContactWithChatRequest
> = z.object({
  chatId: z.string(),
});

export function shareContactWithChatRequestToJSON(
  shareContactWithChatRequest: ShareContactWithChatRequest,
): string {
  return JSON.stringify(
    ShareContactWithChatRequest$outboundSchema.parse(
      shareContactWithChatRequest,
    ),
  );
}
