/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type StartTypingRequest = {
  /**
   * Unique identifier of the chat
   */
  chatId: string;
};

/** @internal */
export type StartTypingRequest$Outbound = {
  chatId: string;
};

/** @internal */
export const StartTypingRequest$outboundSchema: z.ZodMiniType<
  StartTypingRequest$Outbound,
  StartTypingRequest
> = z.object({
  chatId: z.string(),
});

export function startTypingRequestToJSON(
  startTypingRequest: StartTypingRequest,
): string {
  return JSON.stringify(
    StartTypingRequest$outboundSchema.parse(startTypingRequest),
  );
}
