/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";

export type StopTypingRequest = {
  /**
   * Unique identifier of the chat
   */
  chatId: string;
};

/** @internal */
export type StopTypingRequest$Outbound = {
  chatId: string;
};

/** @internal */
export const StopTypingRequest$outboundSchema: z.ZodMiniType<
  StopTypingRequest$Outbound,
  StopTypingRequest
> = z.object({
  chatId: z.string(),
});

export function stopTypingRequestToJSON(
  stopTypingRequest: StopTypingRequest,
): string {
  return JSON.stringify(
    StopTypingRequest$outboundSchema.parse(stopTypingRequest),
  );
}
