/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as components from "../components/index.js";

export type UpdateChatRequest = {
  /**
   * Unique identifier of the chat
   */
  chatId: string;
  body: components.UpdateChatRequest;
};

/** @internal */
export type UpdateChatRequest$Outbound = {
  chatId: string;
  body: components.UpdateChatRequest$Outbound;
};

/** @internal */
export const UpdateChatRequest$outboundSchema: z.ZodMiniType<
  UpdateChatRequest$Outbound,
  UpdateChatRequest
> = z.object({
  chatId: z.string(),
  body: components.UpdateChatRequest$outboundSchema,
});

export function updateChatRequestToJSON(
  updateChatRequest: UpdateChatRequest,
): string {
  return JSON.stringify(
    UpdateChatRequest$outboundSchema.parse(updateChatRequest),
  );
}
