/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import * as components from "../components/index.js";

export type UpdateWebhookSubscriptionRequest = {
  /**
   * Unique identifier of the webhook subscription
   */
  subscriptionId: string;
  body: components.UpdateWebhookSubscriptionRequest;
};

/** @internal */
export type UpdateWebhookSubscriptionRequest$Outbound = {
  subscriptionId: string;
  body: components.UpdateWebhookSubscriptionRequest$Outbound;
};

/** @internal */
export const UpdateWebhookSubscriptionRequest$outboundSchema: z.ZodMiniType<
  UpdateWebhookSubscriptionRequest$Outbound,
  UpdateWebhookSubscriptionRequest
> = z.object({
  subscriptionId: z.string(),
  body: components.UpdateWebhookSubscriptionRequest$outboundSchema,
});

export function updateWebhookSubscriptionRequestToJSON(
  updateWebhookSubscriptionRequest: UpdateWebhookSubscriptionRequest,
): string {
  return JSON.stringify(
    UpdateWebhookSubscriptionRequest$outboundSchema.parse(
      updateWebhookSubscriptionRequest,
    ),
  );
}
