/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the @linqapp/sdk SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx chatsCreateChat.example.ts
 */

import { Linq } from "@linqapp/sdk";

const linq = new Linq({
  bearerAuth: "<YOUR_BEARER_TOKEN_HERE>",
});

async function main() {
  const result = await linq.chats.createChat({
    from: "+12052535597",
    to: [
      "+12052532136",
    ],
    message: {
      parts: [
        {
          type: "text",
          value: "Hello! How can I help you today?",
        },
      ],
    },
  });

  console.log(result);
}

main().catch(console.error);
