/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v4-mini";
import { remap as remap$ } from "../../lib/primitives.js";
import * as types from "../../types/primitives.js";
import * as components from "../components/index.js";
import { LinqError } from "./linq-error.js";

/**
 * Invalid request - validation error
 */
export type ErrorResponseData = {
  error: components.ErrorDetail;
  /**
   * Always false for error responses
   */
  success: boolean;
  /**
   * Unique trace ID for request tracing and debugging
   */
  traceId?: string | undefined;
};

/**
 * Invalid request - validation error
 */
export class ErrorResponse extends LinqError {
  error: components.ErrorDetail;
  /**
   * Always false for error responses
   */
  success: boolean;
  /**
   * Unique trace ID for request tracing and debugging
   */
  traceId?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: ErrorResponseData;

  constructor(
    err: ErrorResponseData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = err.error?.message
      || `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;
    this.success = err.success;
    if (err.traceId != null) this.traceId = err.traceId;

    this.name = "ErrorResponse";
  }
}

/** @internal */
export const ErrorResponse$inboundSchema: z.ZodMiniType<
  ErrorResponse,
  unknown
> = z.pipe(
  z.object({
    error: components.ErrorDetail$inboundSchema,
    success: types.boolean(),
    trace_id: types.optional(types.string()),
    request$: z.custom<Request>(x => x instanceof Request),
    response$: z.custom<Response>(x => x instanceof Response),
    body$: z.string(),
  }),
  z.transform((v) => {
    const remapped = remap$(v, {
      "trace_id": "traceId",
    });

    return new ErrorResponse(remapped, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  }),
);
